// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/proyecto1/analizadores/Lexer.jflex

package proyecto1.analizadores;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int MULTILINE_COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\11\0\1\4\3\0\1\5\1\6\12\7\2\0\1\10"+
    "\1\11\3\0\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\23\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\23\1\37\1\23\4\0\1\40\1\0\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\2\23"+
    "\1\52\1\53\1\54\1\55\1\56\1\23\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\23\1\65\1\23\1\66"+
    "\1\0\1\67\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\1\1\3\2\1\30\4\1\5"+
    "\1\6\2\7\1\10\1\2\1\0\1\11\1\12\17\4"+
    "\1\13\21\4\1\14\1\15\32\4\1\16\17\4\1\17"+
    "\5\4\1\20\6\4\1\21\1\22\7\4\1\23\2\4"+
    "\1\24\3\4\1\25\7\4\1\26\13\4\1\27\4\4"+
    "\1\30\32\4\1\31\1\4\1\32\17\4\1\33\1\34"+
    "\5\4\1\35\4\4\1\36\1\4\1\37\7\4\1\40"+
    "\1\4\1\41\3\4\1\42\4\4\1\43\30\4\1\44"+
    "\27\4\1\45\7\4\1\46\4\4\1\47\20\4\1\50"+
    "\6\4\1\51\1\52\1\4\1\53\1\54\12\4\1\55"+
    "\1\56\2\4\1\57\2\4\1\60\3\4\1\61\6\4"+
    "\1\62\1\4\1\63\1\64\10\4\1\65\4\4\1\66"+
    "\2\4\1\67\5\4\1\70\2\4\1\71\5\4\1\72"+
    "\1\73\3\4\1\74\1\75\4\4\1\76\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[418];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\160\0\250\0\340\0\u0118\0\u0150"+
    "\0\u0188\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u0310"+
    "\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0"+
    "\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0690"+
    "\0\u06c8\0\160\0\160\0\160\0\u0700\0\160\0\u0738\0\u0770"+
    "\0\160\0\160\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888\0\u08c0"+
    "\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48\0\u0a80"+
    "\0\u0ab8\0\u01f8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08"+
    "\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\u0dc8"+
    "\0\u0e00\0\u0e38\0\u0e70\0\160\0\u0770\0\u0ea8\0\u0ee0\0\u0f18"+
    "\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8"+
    "\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u1228\0\u1260\0\u1298"+
    "\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u01f8"+
    "\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570\0\u15a8\0\u15e0"+
    "\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730\0\u1768\0\u01f8"+
    "\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u01f8\0\u18b8\0\u18f0"+
    "\0\u1928\0\u1960\0\u1998\0\u19d0\0\u1a08\0\u01f8\0\u1a40\0\u1a78"+
    "\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58\0\u1b90\0\u01f8\0\u1bc8\0\u1c00"+
    "\0\u01f8\0\u1c38\0\u1c70\0\u1ca8\0\u01f8\0\u1ce0\0\u1d18\0\u1d50"+
    "\0\u1d88\0\u1dc0\0\u1df8\0\u1e30\0\u01f8\0\u1e68\0\u1ea0\0\u1ed8"+
    "\0\u1f10\0\u1f48\0\u1f80\0\u1fb8\0\u1ff0\0\u2028\0\u2060\0\u2098"+
    "\0\u01f8\0\u20d0\0\u2108\0\u2140\0\u2178\0\u01f8\0\u21b0\0\u21e8"+
    "\0\u2220\0\u2258\0\u2290\0\u22c8\0\u2300\0\u2338\0\u2370\0\u23a8"+
    "\0\u23e0\0\u2418\0\u2450\0\u2488\0\u24c0\0\u24f8\0\u2530\0\u2568"+
    "\0\u25a0\0\u25d8\0\u2610\0\u2648\0\u2680\0\u26b8\0\u26f0\0\u2728"+
    "\0\u01f8\0\u2760\0\u01f8\0\u2798\0\u27d0\0\u2808\0\u2840\0\u2878"+
    "\0\u28b0\0\u28e8\0\u2920\0\u2958\0\u2990\0\u29c8\0\u2a00\0\u2a38"+
    "\0\u2a70\0\u2aa8\0\u01f8\0\u01f8\0\u2ae0\0\u2b18\0\u2b50\0\u2b88"+
    "\0\u2bc0\0\u01f8\0\u2bf8\0\u2c30\0\u2c68\0\u2ca0\0\u01f8\0\u2cd8"+
    "\0\u01f8\0\u2d10\0\u2d48\0\u2d80\0\u2db8\0\u2df0\0\u2e28\0\u2e60"+
    "\0\u2e98\0\u2ed0\0\u01f8\0\u2f08\0\u2f40\0\u2f78\0\u01f8\0\u2fb0"+
    "\0\u2fe8\0\u3020\0\u3058\0\u3090\0\u30c8\0\u3100\0\u3138\0\u3170"+
    "\0\u31a8\0\u31e0\0\u3218\0\u3250\0\u3288\0\u32c0\0\u32f8\0\u3330"+
    "\0\u3368\0\u33a0\0\u33d8\0\u3410\0\u3448\0\u3480\0\u34b8\0\u34f0"+
    "\0\u3528\0\u3560\0\u3598\0\u35d0\0\u01f8\0\u3608\0\u3640\0\u3678"+
    "\0\u36b0\0\u36e8\0\u3720\0\u3758\0\u3790\0\u37c8\0\u3800\0\u3838"+
    "\0\u3870\0\u38a8\0\u38e0\0\u3918\0\u3950\0\u3988\0\u39c0\0\u39f8"+
    "\0\u3a30\0\u3a68\0\u3aa0\0\u3ad8\0\u3b10\0\u3b48\0\u3b80\0\u3bb8"+
    "\0\u3bf0\0\u3c28\0\u3c60\0\u3c98\0\u01f8\0\u3cd0\0\u3d08\0\u3d40"+
    "\0\u3d78\0\u01f8\0\u3db0\0\u3de8\0\u3e20\0\u3e58\0\u3e90\0\u3ec8"+
    "\0\u3f00\0\u3f38\0\u3f70\0\u3fa8\0\u3fe0\0\u4018\0\u4050\0\u4088"+
    "\0\u40c0\0\u40f8\0\u01f8\0\u4130\0\u4168\0\u41a0\0\u41d8\0\u4210"+
    "\0\u4248\0\u01f8\0\u01f8\0\u4280\0\u01f8\0\u01f8\0\u42b8\0\u42f0"+
    "\0\u4328\0\u4360\0\u4398\0\u43d0\0\u4408\0\u4440\0\u4478\0\u44b0"+
    "\0\u01f8\0\u01f8\0\u44e8\0\u4520\0\u01f8\0\u4558\0\u4590\0\u01f8"+
    "\0\u45c8\0\u4600\0\u4638\0\u01f8\0\u4670\0\u46a8\0\u46e0\0\u4718"+
    "\0\u4750\0\u4788\0\u01f8\0\u47c0\0\u01f8\0\u47f8\0\u4830\0\u4868"+
    "\0\u48a0\0\u48d8\0\u4910\0\u4948\0\u4980\0\u49b8\0\u01f8\0\u49f0"+
    "\0\u4a28\0\u4a60\0\u4a98\0\u01f8\0\u4ad0\0\u4b08\0\u01f8\0\u4b40"+
    "\0\u4b78\0\u4bb0\0\u4be8\0\u4c20\0\u01f8\0\u4c58\0\u4c90\0\u01f8"+
    "\0\u4cc8\0\u4d00\0\u4d38\0\u4d70\0\u4da8\0\u01f8\0\u01f8\0\u4de0"+
    "\0\u4e18\0\u4e50\0\u01f8\0\u01f8\0\u4e88\0\u4ec0\0\u4ef8\0\u4f30"+
    "\0\u01f8\0\u01f8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[418];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\2\3\1\6\1\7\1\10\1\11"+
    "\1\12\4\13\1\14\1\13\1\15\4\13\1\16\2\13"+
    "\1\17\1\20\3\13\1\21\3\13\1\22\1\13\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\13"+
    "\1\33\1\34\1\35\1\36\1\37\1\13\1\40\1\41"+
    "\1\13\1\42\1\43\4\44\1\45\63\44\72\0\1\4"+
    "\71\0\1\46\1\0\1\47\66\0\1\50\1\0\1\7"+
    "\71\0\1\51\67\0\1\52\65\0\1\13\2\0\17\13"+
    "\1\53\34\13\11\0\1\13\2\0\54\13\11\0\1\13"+
    "\2\0\10\13\1\54\43\13\11\0\1\13\2\0\4\13"+
    "\1\55\47\13\11\0\1\13\2\0\1\56\3\13\1\57"+
    "\47\13\11\0\1\13\2\0\4\13\1\60\47\13\11\0"+
    "\1\13\2\0\7\13\1\61\3\13\1\62\40\13\11\0"+
    "\1\13\2\0\1\63\53\13\11\0\1\13\2\0\43\13"+
    "\1\64\10\13\11\0\1\13\2\0\27\13\1\65\24\13"+
    "\11\0\1\13\2\0\40\13\1\66\13\13\11\0\1\13"+
    "\2\0\27\13\1\67\24\13\11\0\1\13\2\0\33\13"+
    "\1\70\20\13\11\0\1\13\2\0\33\13\1\71\20\13"+
    "\11\0\1\13\2\0\34\13\1\72\5\13\1\73\11\13"+
    "\11\0\1\13\2\0\27\13\1\74\13\13\1\75\10\13"+
    "\11\0\1\13\2\0\27\13\1\76\24\13\11\0\1\13"+
    "\2\0\44\13\1\77\7\13\11\0\1\13\2\0\40\13"+
    "\1\100\13\13\11\0\1\13\2\0\27\13\1\101\13\13"+
    "\1\102\4\13\1\103\3\13\11\0\1\13\2\0\31\13"+
    "\1\104\1\13\1\105\14\13\1\106\3\13\11\0\1\13"+
    "\2\0\36\13\1\107\4\13\1\110\10\13\11\0\1\13"+
    "\2\0\37\13\1\111\14\13\11\0\1\13\2\0\27\13"+
    "\1\112\7\13\1\113\14\13\10\0\1\114\61\0\2\47"+
    "\2\0\64\47\7\0\1\115\67\0\1\13\2\0\2\13"+
    "\1\116\51\13\11\0\1\13\2\0\17\13\1\117\34\13"+
    "\11\0\1\13\2\0\1\120\53\13\11\0\1\13\2\0"+
    "\6\13\1\121\45\13\11\0\1\13\2\0\3\13\1\122"+
    "\50\13\11\0\1\13\2\0\20\13\1\123\33\13\11\0"+
    "\1\13\2\0\10\13\1\124\43\13\11\0\1\13\2\0"+
    "\1\125\53\13\11\0\1\13\2\0\17\13\1\126\34\13"+
    "\11\0\1\13\2\0\42\13\1\127\11\13\11\0\1\13"+
    "\2\0\41\13\1\130\12\13\11\0\1\13\2\0\46\13"+
    "\1\131\5\13\11\0\1\13\2\0\37\13\1\132\14\13"+
    "\11\0\1\13\2\0\47\13\1\133\4\13\11\0\1\13"+
    "\2\0\27\13\1\134\24\13\11\0\1\13\2\0\37\13"+
    "\1\135\14\13\11\0\1\13\2\0\46\13\1\136\5\13"+
    "\11\0\1\13\2\0\52\13\1\137\1\13\11\0\1\13"+
    "\2\0\35\13\1\140\1\13\1\141\7\13\1\142\4\13"+
    "\11\0\1\13\2\0\44\13\1\143\7\13\11\0\1\13"+
    "\2\0\27\13\1\144\24\13\11\0\1\13\2\0\42\13"+
    "\1\145\11\13\11\0\1\13\2\0\50\13\1\146\3\13"+
    "\11\0\1\13\2\0\40\13\1\147\1\13\1\150\11\13"+
    "\11\0\1\13\2\0\43\13\1\151\10\13\11\0\1\13"+
    "\2\0\33\13\1\152\4\13\1\153\13\13\11\0\1\13"+
    "\2\0\31\13\1\154\22\13\11\0\1\13\2\0\33\13"+
    "\1\155\20\13\11\0\1\13\2\0\47\13\1\156\4\13"+
    "\11\0\1\13\2\0\31\13\1\157\22\13\11\0\1\13"+
    "\2\0\45\13\1\160\6\13\11\0\1\13\2\0\47\13"+
    "\1\161\4\13\11\0\1\13\2\0\1\162\53\13\11\0"+
    "\1\13\2\0\4\13\1\163\47\13\11\0\1\13\2\0"+
    "\13\13\1\164\7\13\1\165\30\13\11\0\1\13\2\0"+
    "\10\13\1\166\43\13\11\0\1\13\2\0\10\13\1\167"+
    "\43\13\11\0\1\13\2\0\21\13\1\170\32\13\11\0"+
    "\1\13\2\0\4\13\1\171\47\13\11\0\1\13\2\0"+
    "\20\13\1\172\33\13\11\0\1\13\2\0\26\13\1\173"+
    "\25\13\11\0\1\13\2\0\50\13\1\174\3\13\11\0"+
    "\1\13\2\0\27\13\1\175\24\13\11\0\1\13\2\0"+
    "\33\13\1\176\20\13\11\0\1\13\2\0\40\13\1\177"+
    "\13\13\11\0\1\13\2\0\26\13\1\200\25\13\11\0"+
    "\1\13\2\0\40\13\1\201\13\13\11\0\1\13\2\0"+
    "\47\13\1\202\4\13\11\0\1\13\2\0\47\13\1\203"+
    "\4\13\11\0\1\13\2\0\26\13\1\204\25\13\11\0"+
    "\1\13\2\0\33\13\1\205\20\13\11\0\1\13\2\0"+
    "\42\13\1\206\11\13\11\0\1\13\2\0\31\13\1\207"+
    "\22\13\11\0\1\13\2\0\43\13\1\210\10\13\11\0"+
    "\1\13\2\0\53\13\1\211\11\0\1\13\2\0\32\13"+
    "\1\212\21\13\11\0\1\13\2\0\42\13\1\213\11\13"+
    "\11\0\1\13\2\0\33\13\1\214\20\13\11\0\1\13"+
    "\2\0\45\13\1\215\6\13\11\0\1\13\2\0\32\13"+
    "\1\216\21\13\11\0\1\13\2\0\34\13\1\217\17\13"+
    "\11\0\1\13\2\0\31\13\1\220\22\13\11\0\1\13"+
    "\2\0\42\13\1\221\11\13\11\0\1\13\2\0\27\13"+
    "\1\222\24\13\11\0\1\13\2\0\47\13\1\223\4\13"+
    "\11\0\1\13\2\0\45\13\1\224\6\13\11\0\1\13"+
    "\2\0\36\13\1\225\15\13\11\0\1\13\2\0\15\13"+
    "\1\226\36\13\11\0\1\13\2\0\1\13\1\227\52\13"+
    "\11\0\1\13\2\0\10\13\1\230\43\13\11\0\1\13"+
    "\2\0\25\13\1\231\26\13\11\0\1\13\2\0\2\13"+
    "\1\232\51\13\11\0\1\13\2\0\21\13\1\233\32\13"+
    "\11\0\1\13\2\0\13\13\1\234\40\13\11\0\1\13"+
    "\2\0\7\13\1\235\44\13\11\0\1\13\2\0\2\13"+
    "\1\236\51\13\11\0\1\13\2\0\46\13\1\237\5\13"+
    "\11\0\1\13\2\0\35\13\1\240\16\13\11\0\1\13"+
    "\2\0\33\13\1\241\20\13\11\0\1\13\2\0\40\13"+
    "\1\242\1\243\12\13\11\0\1\13\2\0\37\13\1\244"+
    "\14\13\11\0\1\13\2\0\37\13\1\245\14\13\11\0"+
    "\1\13\2\0\26\13\1\246\25\13\11\0\1\13\2\0"+
    "\36\13\1\247\15\13\11\0\1\13\2\0\26\13\1\250"+
    "\25\13\11\0\1\13\2\0\36\13\1\251\15\13\11\0"+
    "\1\13\2\0\42\13\1\252\11\13\11\0\1\13\2\0"+
    "\33\13\1\253\20\13\11\0\1\13\2\0\43\13\1\254"+
    "\10\13\11\0\1\13\2\0\32\13\1\255\21\13\11\0"+
    "\1\13\2\0\46\13\1\256\5\13\11\0\1\13\2\0"+
    "\37\13\1\257\14\13\11\0\1\13\2\0\26\13\1\260"+
    "\25\13\11\0\1\13\2\0\33\13\1\261\20\13\11\0"+
    "\1\13\2\0\40\13\1\262\13\13\11\0\1\13\2\0"+
    "\43\13\1\263\10\13\11\0\1\13\2\0\37\13\1\264"+
    "\14\13\11\0\1\13\2\0\4\13\1\265\47\13\11\0"+
    "\1\13\2\0\1\266\53\13\11\0\1\13\2\0\15\13"+
    "\1\267\36\13\11\0\1\13\2\0\26\13\1\270\25\13"+
    "\11\0\1\13\2\0\26\13\1\271\25\13\11\0\1\13"+
    "\2\0\1\272\53\13\11\0\1\13\2\0\3\13\1\273"+
    "\50\13\11\0\1\13\2\0\17\13\1\274\34\13\11\0"+
    "\1\13\2\0\33\13\1\275\20\13\11\0\1\13\2\0"+
    "\33\13\1\276\20\13\11\0\1\13\2\0\32\13\1\277"+
    "\21\13\11\0\1\13\2\0\27\13\1\300\24\13\11\0"+
    "\1\13\2\0\43\13\1\301\10\13\11\0\1\13\2\0"+
    "\42\13\1\302\11\13\11\0\1\13\2\0\27\13\1\303"+
    "\24\13\11\0\1\13\2\0\41\13\1\304\12\13\11\0"+
    "\1\13\2\0\33\13\1\305\20\13\11\0\1\13\2\0"+
    "\31\13\1\306\22\13\11\0\1\13\2\0\33\13\1\307"+
    "\20\13\11\0\1\13\2\0\45\13\1\310\6\13\11\0"+
    "\1\13\2\0\41\13\1\311\12\13\11\0\1\13\2\0"+
    "\26\13\1\312\17\13\1\313\5\13\11\0\1\13\2\0"+
    "\42\13\1\314\11\13\11\0\1\13\2\0\36\13\1\315"+
    "\6\13\1\316\1\317\5\13\11\0\1\13\2\0\46\13"+
    "\1\320\5\13\11\0\1\13\2\0\26\13\1\321\25\13"+
    "\11\0\1\13\2\0\45\13\1\322\6\13\11\0\1\13"+
    "\2\0\43\13\1\323\10\13\11\0\1\13\2\0\26\13"+
    "\1\324\25\13\11\0\1\13\2\0\13\13\1\325\40\13"+
    "\11\0\1\13\2\0\6\13\1\326\45\13\11\0\1\13"+
    "\2\0\20\13\1\327\33\13\11\0\1\13\2\0\1\13"+
    "\1\330\52\13\11\0\1\13\2\0\21\13\1\331\32\13"+
    "\11\0\1\13\2\0\26\13\1\332\25\13\11\0\1\13"+
    "\2\0\25\13\1\333\26\13\11\0\1\13\2\0\46\13"+
    "\1\334\5\13\11\0\1\13\2\0\26\13\1\335\25\13"+
    "\11\0\1\13\2\0\26\13\1\336\25\13\11\0\1\13"+
    "\2\0\46\13\1\337\5\13\11\0\1\13\2\0\51\13"+
    "\1\340\2\13\11\0\1\13\2\0\35\13\1\341\16\13"+
    "\11\0\1\13\2\0\40\13\1\342\13\13\11\0\1\13"+
    "\2\0\43\13\1\343\10\13\11\0\1\13\2\0\27\13"+
    "\1\344\24\13\11\0\1\13\2\0\43\13\1\345\10\13"+
    "\11\0\1\13\2\0\42\13\1\346\11\13\11\0\1\13"+
    "\2\0\46\13\1\347\5\13\11\0\1\13\2\0\42\13"+
    "\1\350\11\13\11\0\1\13\2\0\35\13\1\351\16\13"+
    "\11\0\1\13\2\0\33\13\1\352\3\13\1\353\14\13"+
    "\11\0\1\13\2\0\33\13\1\354\20\13\11\0\1\13"+
    "\2\0\31\13\1\355\22\13\11\0\1\13\2\0\46\13"+
    "\1\356\5\13\11\0\1\13\2\0\45\13\1\357\6\13"+
    "\11\0\1\13\2\0\53\13\1\360\11\0\1\13\2\0"+
    "\45\13\1\361\6\13\11\0\1\13\2\0\1\13\1\362"+
    "\52\13\11\0\1\13\2\0\13\13\1\363\40\13\11\0"+
    "\1\13\2\0\26\13\1\364\25\13\11\0\1\13\2\0"+
    "\21\13\1\365\32\13\11\0\1\13\2\0\1\366\53\13"+
    "\11\0\1\13\2\0\4\13\1\367\47\13\11\0\1\13"+
    "\2\0\1\13\1\370\52\13\11\0\1\13\2\0\44\13"+
    "\1\371\7\13\11\0\1\13\2\0\27\13\1\372\24\13"+
    "\11\0\1\13\2\0\47\13\1\373\4\13\11\0\1\13"+
    "\2\0\33\13\1\374\20\13\11\0\1\13\2\0\26\13"+
    "\1\375\25\13\11\0\1\13\2\0\51\13\1\376\2\13"+
    "\11\0\1\13\2\0\40\13\1\377\13\13\11\0\1\13"+
    "\2\0\41\13\1\u0100\12\13\11\0\1\13\2\0\47\13"+
    "\1\u0101\4\13\11\0\1\13\2\0\50\13\1\u0102\3\13"+
    "\11\0\1\13\2\0\27\13\1\u0103\24\13\11\0\1\13"+
    "\2\0\46\13\1\u0104\5\13\11\0\1\13\2\0\46\13"+
    "\1\u0105\5\13\11\0\1\13\2\0\43\13\1\u0106\10\13"+
    "\11\0\1\13\2\0\34\13\1\u0107\17\13\11\0\1\13"+
    "\2\0\43\13\1\u0108\10\13\11\0\1\13\2\0\26\13"+
    "\1\u0109\25\13\11\0\1\13\2\0\26\13\1\u010a\25\13"+
    "\11\0\1\13\2\0\16\13\1\u010b\35\13\11\0\1\13"+
    "\2\0\17\13\1\u010c\34\13\11\0\1\13\2\0\17\13"+
    "\1\u010d\34\13\11\0\1\13\2\0\17\13\1\u010e\34\13"+
    "\11\0\1\13\2\0\13\13\1\u010f\40\13\11\0\1\13"+
    "\2\0\43\13\1\u0110\10\13\11\0\1\13\2\0\31\13"+
    "\1\u0111\22\13\11\0\1\13\2\0\26\13\1\u0112\25\13"+
    "\11\0\1\13\2\0\46\13\1\u0113\5\13\11\0\1\13"+
    "\2\0\44\13\1\u0114\7\13\11\0\1\13\2\0\33\13"+
    "\1\u0115\20\13\11\0\1\13\2\0\47\13\1\u0116\4\13"+
    "\11\0\1\13\2\0\30\13\1\u0117\23\13\11\0\1\13"+
    "\2\0\26\13\1\u0118\25\13\11\0\1\13\2\0\41\13"+
    "\1\u0119\12\13\11\0\1\13\2\0\40\13\1\u011a\13\13"+
    "\11\0\1\13\2\0\47\13\1\u011b\4\13\11\0\1\13"+
    "\2\0\43\13\1\u011c\10\13\11\0\1\13\2\0\45\13"+
    "\1\u011d\6\13\11\0\1\13\2\0\50\13\1\u011e\3\13"+
    "\11\0\1\13\2\0\50\13\1\u011f\3\13\11\0\1\13"+
    "\2\0\30\13\1\u0120\23\13\11\0\1\13\2\0\31\13"+
    "\1\u0121\22\13\11\0\1\13\2\0\13\13\1\u0122\40\13"+
    "\11\0\1\13\2\0\22\13\1\u0123\31\13\11\0\1\13"+
    "\2\0\10\13\1\u0124\43\13\11\0\1\13\2\0\17\13"+
    "\1\u0125\34\13\11\0\1\13\2\0\16\13\1\u0126\35\13"+
    "\11\0\1\13\2\0\37\13\1\u0127\14\13\11\0\1\13"+
    "\2\0\47\13\1\u0128\4\13\11\0\1\13\2\0\42\13"+
    "\1\u0129\11\13\11\0\1\13\2\0\26\13\1\u012a\25\13"+
    "\11\0\1\13\2\0\43\13\1\u012b\10\13\11\0\1\13"+
    "\2\0\36\13\1\u012c\15\13\11\0\1\13\2\0\43\13"+
    "\1\u012d\10\13\11\0\1\13\2\0\36\13\1\u012e\6\13"+
    "\1\u012f\1\u0130\5\13\11\0\1\13\2\0\30\13\1\u0131"+
    "\23\13\11\0\1\13\2\0\47\13\1\u0132\4\13\11\0"+
    "\1\13\2\0\43\13\1\u0133\10\13\11\0\1\13\2\0"+
    "\50\13\1\u0134\3\13\11\0\1\13\2\0\33\13\1\u0135"+
    "\20\13\11\0\1\13\2\0\40\13\1\u0136\13\13\11\0"+
    "\1\13\2\0\42\13\1\u0137\11\13\11\0\1\13\2\0"+
    "\43\13\1\u0138\10\13\11\0\1\13\2\0\43\13\1\u0139"+
    "\10\13\11\0\1\13\2\0\21\13\1\u013a\32\13\11\0"+
    "\1\13\2\0\15\13\1\u013b\36\13\11\0\1\13\2\0"+
    "\12\13\1\u013c\41\13\11\0\1\13\2\0\10\13\1\u013d"+
    "\43\13\11\0\1\13\2\0\2\13\1\u013e\51\13\11\0"+
    "\1\13\2\0\42\13\1\u013f\11\13\11\0\1\13\2\0"+
    "\37\13\1\u0140\14\13\11\0\1\13\2\0\26\13\1\u0141"+
    "\25\13\11\0\1\13\2\0\31\13\1\u0142\22\13\11\0"+
    "\1\13\2\0\37\13\1\u0143\14\13\11\0\1\13\2\0"+
    "\26\13\1\u0144\25\13\11\0\1\13\2\0\26\13\1\u0145"+
    "\25\13\11\0\1\13\2\0\33\13\1\u0146\3\13\1\u0147"+
    "\14\13\11\0\1\13\2\0\33\13\1\u0148\20\13\11\0"+
    "\1\13\2\0\31\13\1\u0149\22\13\11\0\1\13\2\0"+
    "\33\13\1\u014a\20\13\11\0\1\13\2\0\36\13\1\u014b"+
    "\15\13\11\0\1\13\2\0\45\13\1\u014c\6\13\11\0"+
    "\1\13\2\0\45\13\1\u014d\6\13\11\0\1\13\2\0"+
    "\26\13\1\u014e\25\13\11\0\1\13\2\0\32\13\1\u014f"+
    "\21\13\11\0\1\13\2\0\42\13\1\u0150\11\13\11\0"+
    "\1\13\2\0\41\13\1\u0151\12\13\11\0\1\13\2\0"+
    "\4\13\1\u0152\47\13\11\0\1\13\2\0\4\13\1\u0153"+
    "\47\13\11\0\1\13\2\0\4\13\1\u0154\47\13\11\0"+
    "\1\13\2\0\12\13\1\u0155\41\13\11\0\1\13\2\0"+
    "\47\13\1\u0156\4\13\11\0\1\13\2\0\43\13\1\u0157"+
    "\10\13\11\0\1\13\2\0\41\13\1\u0158\12\13\11\0"+
    "\1\13\2\0\43\13\1\u0159\10\13\11\0\1\13\2\0"+
    "\42\13\1\u015a\11\13\11\0\1\13\2\0\51\13\1\u015b"+
    "\2\13\11\0\1\13\2\0\44\13\1\u015c\7\13\11\0"+
    "\1\13\2\0\27\13\1\u015d\24\13\11\0\1\13\2\0"+
    "\46\13\1\u015e\5\13\11\0\1\13\2\0\46\13\1\u015f"+
    "\5\13\11\0\1\13\2\0\43\13\1\u0160\10\13\11\0"+
    "\1\13\2\0\45\13\1\u0161\6\13\11\0\1\13\2\0"+
    "\53\13\1\u0162\11\0\1\13\2\0\31\13\1\u0163\22\13"+
    "\11\0\1\13\2\0\32\13\1\u0164\21\13\11\0\1\13"+
    "\2\0\46\13\1\u0165\5\13\11\0\1\13\2\0\50\13"+
    "\1\u0166\3\13\11\0\1\13\2\0\30\13\1\u0167\23\13"+
    "\11\0\1\13\2\0\17\13\1\u0168\34\13\11\0\1\13"+
    "\2\0\42\13\1\u0169\11\13\11\0\1\13\2\0\43\13"+
    "\1\u016a\10\13\11\0\1\13\2\0\50\13\1\u016b\3\13"+
    "\11\0\1\13\2\0\47\13\1\u016c\4\13\11\0\1\13"+
    "\2\0\37\13\1\u016d\14\13\11\0\1\13\2\0\43\13"+
    "\1\u016e\10\13\11\0\1\13\2\0\40\13\1\u016f\13\13"+
    "\11\0\1\13\2\0\47\13\1\u0170\4\13\11\0\1\13"+
    "\2\0\43\13\1\u0171\10\13\11\0\1\13\2\0\45\13"+
    "\1\u0172\6\13\11\0\1\13\2\0\33\13\1\u0173\20\13"+
    "\11\0\1\13\2\0\33\13\1\u0174\20\13\11\0\1\13"+
    "\2\0\46\13\1\u0175\5\13\11\0\1\13\2\0\43\13"+
    "\1\u0176\10\13\11\0\1\13\2\0\26\13\1\u0177\25\13"+
    "\11\0\1\13\2\0\51\13\1\u0178\2\13\11\0\1\13"+
    "\2\0\42\13\1\u0179\11\13\11\0\1\13\2\0\31\13"+
    "\1\u017a\22\13\11\0\1\13\2\0\37\13\1\u017b\14\13"+
    "\11\0\1\13\2\0\47\13\1\u017c\4\13\11\0\1\13"+
    "\2\0\43\13\1\u017d\10\13\11\0\1\13\2\0\50\13"+
    "\1\u017e\3\13\11\0\1\13\2\0\33\13\1\u017f\20\13"+
    "\11\0\1\13\2\0\34\13\1\u0180\17\13\11\0\1\13"+
    "\2\0\26\13\1\u0181\25\13\11\0\1\13\2\0\44\13"+
    "\1\u0182\7\13\11\0\1\13\2\0\33\13\1\u0183\20\13"+
    "\11\0\1\13\2\0\47\13\1\u0184\4\13\11\0\1\13"+
    "\2\0\47\13\1\u0185\4\13\11\0\1\13\2\0\42\13"+
    "\1\u0186\11\13\11\0\1\13\2\0\36\13\1\u0187\15\13"+
    "\11\0\1\13\2\0\45\13\1\u0188\6\13\11\0\1\13"+
    "\2\0\45\13\1\u0189\6\13\11\0\1\13\2\0\33\13"+
    "\1\u018a\20\13\11\0\1\13\2\0\44\13\1\u018b\7\13"+
    "\11\0\1\13\2\0\33\13\1\u018c\20\13\11\0\1\13"+
    "\2\0\46\13\1\u018d\5\13\11\0\1\13\2\0\43\13"+
    "\1\u018e\10\13\11\0\1\13\2\0\47\13\1\u018f\4\13"+
    "\11\0\1\13\2\0\53\13\1\u0190\11\0\1\13\2\0"+
    "\31\13\1\u0191\22\13\11\0\1\13\2\0\42\13\1\u0192"+
    "\11\13\11\0\1\13\2\0\43\13\1\u0193\10\13\11\0"+
    "\1\13\2\0\42\13\1\u0194\11\13\11\0\1\13\2\0"+
    "\45\13\1\u0195\6\13\11\0\1\13\2\0\46\13\1\u0196"+
    "\5\13\11\0\1\13\2\0\33\13\1\u0197\20\13\11\0"+
    "\1\13\2\0\46\13\1\u0198\5\13\11\0\1\13\2\0"+
    "\37\13\1\u0199\14\13\11\0\1\13\2\0\27\13\1\u019a"+
    "\24\13\11\0\1\13\2\0\53\13\1\u019b\11\0\1\13"+
    "\2\0\33\13\1\u019c\20\13\11\0\1\13\2\0\42\13"+
    "\1\u019d\11\13\11\0\1\13\2\0\40\13\1\u019e\13\13"+
    "\11\0\1\13\2\0\47\13\1\u019f\4\13\11\0\1\13"+
    "\2\0\47\13\1\u01a0\4\13\11\0\1\13\2\0\46\13"+
    "\1\u01a1\5\13\11\0\1\13\2\0\53\13\1\u01a2\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[20328];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\35\1\3\11\1\1\1\11\1\1\1\0"+
    "\2\11\41\1\1\11\u0156\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[418];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Léxico: " + yytext() + " en línea " + (yyline + 1)); 
    // Aquí luego agregaremos la lógica para guardar el error en tu reporte visual
            }
          // fall through
          case 64: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 65: break;
          case 3:
            { return new Symbol(sym.INTEGER, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 66: break;
          case 4:
            { return new Symbol(sym.ID, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 67: break;
          case 5:
            { return new Symbol(sym.LBRACE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 68: break;
          case 6:
            { return new Symbol(sym.RBRACE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 69: break;
          case 7:
            { /* Ignorar contenido */
            }
          // fall through
          case 70: break;
          case 8:
            { yybegin(MULTILINE_COMMENT);
            }
          // fall through
          case 71: break;
          case 9:
            { return new Symbol(sym.LTEQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 72: break;
          case 10:
            { return new Symbol(sym.EQEQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 73: break;
          case 11:
            { return new Symbol(sym.IF, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 74: break;
          case 12:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 75: break;
          case 13:
            { return new Symbol(sym.FLOAT, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 76: break;
          case 14:
            { return new Symbol(sym.RUN, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 77: break;
          case 15:
            { return new Symbol(sym.REST, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 78: break;
          case 16:
            { return new Symbol(sym.ELSE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 79: break;
          case 17:
            { return new Symbol(sym.MAGE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 80: break;
          case 18:
            { return new Symbol(sym.MAIN, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 81: break;
          case 19:
            { return new Symbol(sym.SEED, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 82: break;
          case 20:
            { return new Symbol(sym.THEN, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 83: break;
          case 21:
            { return new Symbol(sym.WITH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 84: break;
          case 22:
            { return new Symbol(sym.SLASH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 85: break;
          case 23:
            { return new Symbol(sym.MATCH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 86: break;
          case 24:
            { return new Symbol(sym.RULES, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 87: break;
          case 25:
            { return new Symbol(sym.RANDOM, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 88: break;
          case 26:
            { return new Symbol(sym.ROUNDS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 89: break;
          case 27:
            { return new Symbol(sym.WAR_CRY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 90: break;
          case 28:
            { return new Symbol(sym.BONUSES, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 91: break;
          case 29:
            { return new Symbol(sym.INITIAL, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 92: break;
          case 30:
            { return new Symbol(sym.PLAYERS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 93: break;
          case 31:
            { return new Symbol(sym.SCORING, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 94: break;
          case 32:
            { return new Symbol(sym.WARRIOR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 95: break;
          case 33:
            { return new Symbol(sym.FIREBALL, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 96: break;
          case 34:
            { return new Symbol(sym.MEDITATE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 97: break;
          case 35:
            { return new Symbol(sym.GET_MOVE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 98: break;
          case 36:
            { return new Symbol(sym.LAST_MOVE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 99: break;
          case 37:
            { return new Symbol(sym.MAGE_COMBO, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 100: break;
          case 38:
            { return new Symbol(sym.SELF_SCORE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 101: break;
          case 39:
            { return new Symbol(sym.ARCANE_BOLT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 102: break;
          case 40:
            { return new Symbol(sym.SELF_HEALTH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 103: break;
          case 41:
            { return new Symbol(sym.HEALING_RUNE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 104: break;
          case 42:
            { return new Symbol(sym.HEAVY_STRIKE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 105: break;
          case 43:
            { return new Symbol(sym.SHIELD_BLOCK, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 106: break;
          case 44:
            { return new Symbol(sym.DAMAGE_POINT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 107: break;
          case 45:
            { return new Symbol(sym.ROUND_NUMBER, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 108: break;
          case 46:
            { return new Symbol(sym.SELF_HISTORY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 109: break;
          case 47:
            { return new Symbol(sym.TOTAL_ROUNDS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 110: break;
          case 48:
            { return new Symbol(sym.MAGIC_BARRIER, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 111: break;
          case 49:
            { return new Symbol(sym.HEALING_POINT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 112: break;
          case 50:
            { return new Symbol(sym.SELF_RESOURCE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 113: break;
          case 51:
            { return new Symbol(sym.VICTORY_BONUS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 114: break;
          case 52:
            { return new Symbol(sym.WARRIOR_COMBO, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 115: break;
          case 53:
            { return new Symbol(sym.OPPONENT_SCORE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 116: break;
          case 54:
            { return new Symbol(sym.GET_MOVES_COUNT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 117: break;
          case 55:
            { return new Symbol(sym.OPPONENT_HEALTH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 118: break;
          case 56:
            { return new Symbol(sym.GET_LAST_N_MOVES, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 119: break;
          case 57:
            { return new Symbol(sym.OPPONENT_HISTORY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 120: break;
          case 58:
            { return new Symbol(sym.MAGE_COMBO_POINTS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 121: break;
          case 59:
            { return new Symbol(sym.OPPONENT_RESOURCE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 122: break;
          case 60:
            { return new Symbol(sym.LOW_HEALTH_VICTORY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 123: break;
          case 61:
            { return new Symbol(sym.SUCCESSFUL_DEFENSE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 124: break;
          case 62:
            { return new Symbol(sym.WARRIOR_COMBO_POINTS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 125: break;
          case 63:
            { return new Symbol(sym.FAILED_ACTION_PENALTY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
