// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/proyecto1/analizadores/Lexer.jflex

package proyecto1.analizadores;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int MULTILINE_COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\4\0\1\5\1\0\1\6\1\7\1\10\1\0"+
    "\1\11\1\0\1\12\1\13\12\14\1\15\1\0\1\16"+
    "\1\17\1\20\2\0\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\2\32\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\32\1\46\1\32\1\47\1\0\1\50\1\0"+
    "\1\51\1\0\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\2\32\1\63\1\64\1\65\1\66"+
    "\1\67\1\32\1\70\1\71\1\72\1\73\1\74\1\75"+
    "\1\32\1\76\1\32\1\77\1\100\1\101\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\1\1\12\10\13\1\14"+
    "\1\15\20\13\1\16\1\1\1\17\2\20\1\21\1\22"+
    "\1\23\1\2\1\0\1\24\1\25\1\26\17\13\1\27"+
    "\21\13\1\30\1\31\1\32\32\13\1\33\17\13\1\34"+
    "\5\13\1\35\6\13\1\36\1\37\7\13\1\40\2\13"+
    "\1\41\3\13\1\42\7\13\1\43\13\13\1\44\4\13"+
    "\1\45\32\13\1\46\1\13\1\47\17\13\1\50\1\51"+
    "\5\13\1\52\4\13\1\53\1\13\1\54\7\13\1\55"+
    "\1\13\1\56\3\13\1\57\4\13\1\60\30\13\1\61"+
    "\27\13\1\62\7\13\1\63\4\13\1\64\20\13\1\65"+
    "\6\13\1\66\1\67\1\13\1\70\1\71\12\13\1\72"+
    "\1\73\2\13\1\74\2\13\1\75\3\13\1\76\6\13"+
    "\1\77\1\13\1\100\1\101\10\13\1\102\4\13\1\103"+
    "\2\13\1\104\5\13\1\105\2\13\1\106\5\13\1\107"+
    "\1\110\3\13\1\111\1\112\4\13\1\113\1\114";

  private static int [] zzUnpackAction() {
    int [] result = new int[432];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\204\0\306\0\u0108\0\u014a\0\204"+
    "\0\204\0\204\0\u018c\0\u01ce\0\204\0\u0210\0\u0252\0\u0294"+
    "\0\u02d6\0\u0318\0\u035a\0\u039c\0\u03de\0\u0420\0\u0462\0\u04a4"+
    "\0\204\0\204\0\u04e6\0\u0528\0\u056a\0\u05ac\0\u05ee\0\u0630"+
    "\0\u0672\0\u06b4\0\u06f6\0\u0738\0\u077a\0\u07bc\0\u07fe\0\u0840"+
    "\0\u0882\0\u08c4\0\204\0\u0906\0\204\0\204\0\u0948\0\204"+
    "\0\204\0\204\0\u098a\0\u09cc\0\204\0\204\0\204\0\u0a0e"+
    "\0\u0a50\0\u0a92\0\u0ad4\0\u0b16\0\u0b58\0\u0b9a\0\u0bdc\0\u0c1e"+
    "\0\u0c60\0\u0ca2\0\u0ce4\0\u0d26\0\u0d68\0\u0daa\0\u0318\0\u0dec"+
    "\0\u0e2e\0\u0e70\0\u0eb2\0\u0ef4\0\u0f36\0\u0f78\0\u0fba\0\u0ffc"+
    "\0\u103e\0\u1080\0\u10c2\0\u1104\0\u1146\0\u1188\0\u11ca\0\u120c"+
    "\0\204\0\204\0\u09cc\0\u124e\0\u1290\0\u12d2\0\u1314\0\u1356"+
    "\0\u1398\0\u13da\0\u141c\0\u145e\0\u14a0\0\u14e2\0\u1524\0\u1566"+
    "\0\u15a8\0\u15ea\0\u162c\0\u166e\0\u16b0\0\u16f2\0\u1734\0\u1776"+
    "\0\u17b8\0\u17fa\0\u183c\0\u187e\0\u18c0\0\u0318\0\u1902\0\u1944"+
    "\0\u1986\0\u19c8\0\u1a0a\0\u1a4c\0\u1a8e\0\u1ad0\0\u1b12\0\u1b54"+
    "\0\u1b96\0\u1bd8\0\u1c1a\0\u1c5c\0\u1c9e\0\u0318\0\u1ce0\0\u1d22"+
    "\0\u1d64\0\u1da6\0\u1de8\0\u0318\0\u1e2a\0\u1e6c\0\u1eae\0\u1ef0"+
    "\0\u1f32\0\u1f74\0\u1fb6\0\u0318\0\u1ff8\0\u203a\0\u207c\0\u20be"+
    "\0\u2100\0\u2142\0\u2184\0\u0318\0\u21c6\0\u2208\0\u0318\0\u224a"+
    "\0\u228c\0\u22ce\0\u0318\0\u2310\0\u2352\0\u2394\0\u23d6\0\u2418"+
    "\0\u245a\0\u249c\0\u0318\0\u24de\0\u2520\0\u2562\0\u25a4\0\u25e6"+
    "\0\u2628\0\u266a\0\u26ac\0\u26ee\0\u2730\0\u2772\0\u0318\0\u27b4"+
    "\0\u27f6\0\u2838\0\u287a\0\u0318\0\u28bc\0\u28fe\0\u2940\0\u2982"+
    "\0\u29c4\0\u2a06\0\u2a48\0\u2a8a\0\u2acc\0\u2b0e\0\u2b50\0\u2b92"+
    "\0\u2bd4\0\u2c16\0\u2c58\0\u2c9a\0\u2cdc\0\u2d1e\0\u2d60\0\u2da2"+
    "\0\u2de4\0\u2e26\0\u2e68\0\u2eaa\0\u2eec\0\u2f2e\0\u0318\0\u2f70"+
    "\0\u0318\0\u2fb2\0\u2ff4\0\u3036\0\u3078\0\u30ba\0\u30fc\0\u313e"+
    "\0\u3180\0\u31c2\0\u3204\0\u3246\0\u3288\0\u32ca\0\u330c\0\u334e"+
    "\0\u0318\0\u0318\0\u3390\0\u33d2\0\u3414\0\u3456\0\u3498\0\u0318"+
    "\0\u34da\0\u351c\0\u355e\0\u35a0\0\u0318\0\u35e2\0\u0318\0\u3624"+
    "\0\u3666\0\u36a8\0\u36ea\0\u372c\0\u376e\0\u37b0\0\u37f2\0\u3834"+
    "\0\u0318\0\u3876\0\u38b8\0\u38fa\0\u0318\0\u393c\0\u397e\0\u39c0"+
    "\0\u3a02\0\u3a44\0\u3a86\0\u3ac8\0\u3b0a\0\u3b4c\0\u3b8e\0\u3bd0"+
    "\0\u3c12\0\u3c54\0\u3c96\0\u3cd8\0\u3d1a\0\u3d5c\0\u3d9e\0\u3de0"+
    "\0\u3e22\0\u3e64\0\u3ea6\0\u3ee8\0\u3f2a\0\u3f6c\0\u3fae\0\u3ff0"+
    "\0\u4032\0\u4074\0\u0318\0\u40b6\0\u40f8\0\u413a\0\u417c\0\u41be"+
    "\0\u4200\0\u4242\0\u4284\0\u42c6\0\u4308\0\u434a\0\u438c\0\u43ce"+
    "\0\u4410\0\u4452\0\u4494\0\u44d6\0\u4518\0\u455a\0\u459c\0\u45de"+
    "\0\u4620\0\u4662\0\u46a4\0\u46e6\0\u4728\0\u476a\0\u47ac\0\u47ee"+
    "\0\u4830\0\u4872\0\u0318\0\u48b4\0\u48f6\0\u4938\0\u497a\0\u0318"+
    "\0\u49bc\0\u49fe\0\u4a40\0\u4a82\0\u4ac4\0\u4b06\0\u4b48\0\u4b8a"+
    "\0\u4bcc\0\u4c0e\0\u4c50\0\u4c92\0\u4cd4\0\u4d16\0\u4d58\0\u4d9a"+
    "\0\u0318\0\u4ddc\0\u4e1e\0\u4e60\0\u4ea2\0\u4ee4\0\u4f26\0\u0318"+
    "\0\u0318\0\u4f68\0\u0318\0\u0318\0\u4faa\0\u4fec\0\u502e\0\u5070"+
    "\0\u50b2\0\u50f4\0\u5136\0\u5178\0\u51ba\0\u51fc\0\u0318\0\u0318"+
    "\0\u523e\0\u5280\0\u0318\0\u52c2\0\u5304\0\u0318\0\u5346\0\u5388"+
    "\0\u53ca\0\u0318\0\u540c\0\u544e\0\u5490\0\u54d2\0\u5514\0\u5556"+
    "\0\u0318\0\u5598\0\u0318\0\u55da\0\u561c\0\u565e\0\u56a0\0\u56e2"+
    "\0\u5724\0\u5766\0\u57a8\0\u57ea\0\u0318\0\u582c\0\u586e\0\u58b0"+
    "\0\u58f2\0\u0318\0\u5934\0\u5976\0\u0318\0\u59b8\0\u59fa\0\u5a3c"+
    "\0\u5a7e\0\u5ac0\0\u0318\0\u5b02\0\u5b44\0\u0318\0\u5b86\0\u5bc8"+
    "\0\u5c0a\0\u5c4c\0\u5c8e\0\u0318\0\u0318\0\u5cd0\0\u5d12\0\u5d54"+
    "\0\u0318\0\u0318\0\u5d96\0\u5dd8\0\u5e1a\0\u5e5c\0\u0318\0\u0318";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[432];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\3\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\4\22\1\23\1\22\1\24\4\22\1\25\2\22"+
    "\1\26\1\27\3\22\1\30\1\22\1\31\1\32\2\22"+
    "\1\33\1\22\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\22\1\44\1\45\1\46\1\47\1\50"+
    "\1\22\1\51\1\52\1\22\1\53\1\54\1\55\10\56"+
    "\1\57\71\56\104\0\1\4\116\0\1\60\67\0\1\61"+
    "\104\0\1\62\2\0\1\63\100\0\1\64\1\0\1\14"+
    "\104\0\1\65\101\0\1\66\101\0\1\67\76\0\1\22"+
    "\4\0\17\22\1\70\6\22\2\0\26\22\17\0\1\22"+
    "\4\0\26\22\2\0\26\22\17\0\1\22\4\0\10\22"+
    "\1\71\15\22\2\0\26\22\17\0\1\22\4\0\4\22"+
    "\1\72\21\22\2\0\26\22\17\0\1\22\4\0\1\73"+
    "\3\22\1\74\21\22\2\0\26\22\17\0\1\22\4\0"+
    "\4\22\1\75\21\22\2\0\26\22\17\0\1\22\4\0"+
    "\7\22\1\76\3\22\1\77\12\22\2\0\26\22\17\0"+
    "\1\22\4\0\1\100\25\22\2\0\26\22\17\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\101\10\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\22\1\102\24\22\17\0\1\22"+
    "\4\0\26\22\2\0\12\22\1\103\13\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\22\1\104\24\22\17\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\105\20\22\17\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\106\20\22\17\0\1\22"+
    "\4\0\26\22\2\0\6\22\1\107\5\22\1\110\11\22"+
    "\17\0\1\22\4\0\26\22\2\0\1\22\1\111\13\22"+
    "\1\112\10\22\17\0\1\22\4\0\26\22\2\0\1\22"+
    "\1\113\24\22\17\0\1\22\4\0\26\22\2\0\16\22"+
    "\1\114\7\22\17\0\1\22\4\0\26\22\2\0\12\22"+
    "\1\115\13\22\17\0\1\22\4\0\26\22\2\0\1\22"+
    "\1\116\13\22\1\117\4\22\1\120\3\22\17\0\1\22"+
    "\4\0\26\22\2\0\3\22\1\121\1\22\1\122\14\22"+
    "\1\123\3\22\17\0\1\22\4\0\26\22\2\0\10\22"+
    "\1\124\4\22\1\125\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\11\22\1\126\14\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\22\1\127\7\22\1\130\14\22\103\0\1\131"+
    "\14\0\1\132\66\0\2\63\2\0\76\63\14\0\1\133"+
    "\101\0\1\22\4\0\2\22\1\134\23\22\2\0\26\22"+
    "\17\0\1\22\4\0\17\22\1\135\6\22\2\0\26\22"+
    "\17\0\1\22\4\0\1\136\25\22\2\0\26\22\17\0"+
    "\1\22\4\0\6\22\1\137\17\22\2\0\26\22\17\0"+
    "\1\22\4\0\3\22\1\140\22\22\2\0\26\22\17\0"+
    "\1\22\4\0\20\22\1\141\5\22\2\0\26\22\17\0"+
    "\1\22\4\0\10\22\1\142\15\22\2\0\26\22\17\0"+
    "\1\22\4\0\1\143\25\22\2\0\26\22\17\0\1\22"+
    "\4\0\17\22\1\144\6\22\2\0\26\22\17\0\1\22"+
    "\4\0\26\22\2\0\14\22\1\145\11\22\17\0\1\22"+
    "\4\0\26\22\2\0\13\22\1\146\12\22\17\0\1\22"+
    "\4\0\26\22\2\0\20\22\1\147\5\22\17\0\1\22"+
    "\4\0\26\22\2\0\11\22\1\150\14\22\17\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\151\4\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\22\1\152\24\22\17\0\1\22"+
    "\4\0\26\22\2\0\11\22\1\153\14\22\17\0\1\22"+
    "\4\0\26\22\2\0\20\22\1\154\5\22\17\0\1\22"+
    "\4\0\26\22\2\0\24\22\1\155\1\22\17\0\1\22"+
    "\4\0\26\22\2\0\7\22\1\156\1\22\1\157\7\22"+
    "\1\160\4\22\17\0\1\22\4\0\26\22\2\0\16\22"+
    "\1\161\7\22\17\0\1\22\4\0\26\22\2\0\1\22"+
    "\1\162\24\22\17\0\1\22\4\0\26\22\2\0\14\22"+
    "\1\163\11\22\17\0\1\22\4\0\26\22\2\0\22\22"+
    "\1\164\3\22\17\0\1\22\4\0\26\22\2\0\12\22"+
    "\1\165\1\22\1\166\11\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\167\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\170\4\22\1\171\13\22\17\0\1\22"+
    "\4\0\26\22\2\0\3\22\1\172\22\22\17\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\173\20\22\17\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\174\4\22\17\0\1\22"+
    "\4\0\26\22\2\0\3\22\1\175\22\22\17\0\1\22"+
    "\4\0\26\22\2\0\17\22\1\176\6\22\17\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\177\4\22\17\0\1\22"+
    "\4\0\1\200\25\22\2\0\26\22\17\0\1\22\4\0"+
    "\4\22\1\201\21\22\2\0\26\22\17\0\1\22\4\0"+
    "\13\22\1\202\7\22\1\203\2\22\2\0\26\22\17\0"+
    "\1\22\4\0\10\22\1\204\15\22\2\0\26\22\17\0"+
    "\1\22\4\0\10\22\1\205\15\22\2\0\26\22\17\0"+
    "\1\22\4\0\21\22\1\206\4\22\2\0\26\22\17\0"+
    "\1\22\4\0\4\22\1\207\21\22\2\0\26\22\17\0"+
    "\1\22\4\0\20\22\1\210\5\22\2\0\26\22\17\0"+
    "\1\22\4\0\26\22\2\0\1\211\25\22\17\0\1\22"+
    "\4\0\26\22\2\0\22\22\1\212\3\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\22\1\213\24\22\17\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\214\20\22\17\0\1\22"+
    "\4\0\26\22\2\0\12\22\1\215\13\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\216\25\22\17\0\1\22\4\0"+
    "\26\22\2\0\12\22\1\217\13\22\17\0\1\22\4\0"+
    "\26\22\2\0\21\22\1\220\4\22\17\0\1\22\4\0"+
    "\26\22\2\0\21\22\1\221\4\22\17\0\1\22\4\0"+
    "\26\22\2\0\1\222\25\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\223\20\22\17\0\1\22\4\0\26\22"+
    "\2\0\14\22\1\224\11\22\17\0\1\22\4\0\26\22"+
    "\2\0\3\22\1\225\22\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\226\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\25\22\1\227\17\0\1\22\4\0\26\22\2\0"+
    "\4\22\1\230\21\22\17\0\1\22\4\0\26\22\2\0"+
    "\14\22\1\231\11\22\17\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\232\20\22\17\0\1\22\4\0\26\22\2\0"+
    "\17\22\1\233\6\22\17\0\1\22\4\0\26\22\2\0"+
    "\4\22\1\234\21\22\17\0\1\22\4\0\26\22\2\0"+
    "\6\22\1\235\17\22\17\0\1\22\4\0\26\22\2\0"+
    "\3\22\1\236\22\22\17\0\1\22\4\0\26\22\2\0"+
    "\14\22\1\237\11\22\17\0\1\22\4\0\26\22\2\0"+
    "\1\22\1\240\24\22\17\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\241\4\22\17\0\1\22\4\0\26\22\2\0"+
    "\17\22\1\242\6\22\17\0\1\22\4\0\26\22\2\0"+
    "\10\22\1\243\15\22\17\0\1\22\4\0\15\22\1\244"+
    "\10\22\2\0\26\22\17\0\1\22\4\0\1\22\1\245"+
    "\24\22\2\0\26\22\17\0\1\22\4\0\10\22\1\246"+
    "\15\22\2\0\26\22\17\0\1\22\4\0\25\22\1\247"+
    "\2\0\26\22\17\0\1\22\4\0\2\22\1\250\23\22"+
    "\2\0\26\22\17\0\1\22\4\0\21\22\1\251\4\22"+
    "\2\0\26\22\17\0\1\22\4\0\13\22\1\252\12\22"+
    "\2\0\26\22\17\0\1\22\4\0\7\22\1\253\16\22"+
    "\2\0\26\22\17\0\1\22\4\0\2\22\1\254\23\22"+
    "\2\0\26\22\17\0\1\22\4\0\26\22\2\0\20\22"+
    "\1\255\5\22\17\0\1\22\4\0\26\22\2\0\7\22"+
    "\1\256\16\22\17\0\1\22\4\0\26\22\2\0\5\22"+
    "\1\257\20\22\17\0\1\22\4\0\26\22\2\0\12\22"+
    "\1\260\1\261\12\22\17\0\1\22\4\0\26\22\2\0"+
    "\11\22\1\262\14\22\17\0\1\22\4\0\26\22\2\0"+
    "\11\22\1\263\14\22\17\0\1\22\4\0\26\22\2\0"+
    "\1\264\25\22\17\0\1\22\4\0\26\22\2\0\10\22"+
    "\1\265\15\22\17\0\1\22\4\0\26\22\2\0\1\266"+
    "\25\22\17\0\1\22\4\0\26\22\2\0\10\22\1\267"+
    "\15\22\17\0\1\22\4\0\26\22\2\0\14\22\1\270"+
    "\11\22\17\0\1\22\4\0\26\22\2\0\5\22\1\271"+
    "\20\22\17\0\1\22\4\0\26\22\2\0\15\22\1\272"+
    "\10\22\17\0\1\22\4\0\26\22\2\0\4\22\1\273"+
    "\21\22\17\0\1\22\4\0\26\22\2\0\20\22\1\274"+
    "\5\22\17\0\1\22\4\0\26\22\2\0\11\22\1\275"+
    "\14\22\17\0\1\22\4\0\26\22\2\0\1\276\25\22"+
    "\17\0\1\22\4\0\26\22\2\0\5\22\1\277\20\22"+
    "\17\0\1\22\4\0\26\22\2\0\12\22\1\300\13\22"+
    "\17\0\1\22\4\0\26\22\2\0\15\22\1\301\10\22"+
    "\17\0\1\22\4\0\26\22\2\0\11\22\1\302\14\22"+
    "\17\0\1\22\4\0\4\22\1\303\21\22\2\0\26\22"+
    "\17\0\1\22\4\0\1\304\25\22\2\0\26\22\17\0"+
    "\1\22\4\0\15\22\1\305\10\22\2\0\26\22\17\0"+
    "\1\22\4\0\26\22\2\0\1\306\25\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\307\25\22\17\0\1\22\4\0"+
    "\1\310\25\22\2\0\26\22\17\0\1\22\4\0\3\22"+
    "\1\311\22\22\2\0\26\22\17\0\1\22\4\0\17\22"+
    "\1\312\6\22\2\0\26\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\313\20\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\314\20\22\17\0\1\22\4\0\26\22"+
    "\2\0\4\22\1\315\21\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\22\1\316\24\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\317\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\14\22\1\320\11\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\22\1\321\24\22\17\0\1\22\4\0\26\22"+
    "\2\0\13\22\1\322\12\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\323\20\22\17\0\1\22\4\0\26\22"+
    "\2\0\3\22\1\324\22\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\325\20\22\17\0\1\22\4\0\26\22"+
    "\2\0\17\22\1\326\6\22\17\0\1\22\4\0\26\22"+
    "\2\0\13\22\1\327\12\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\330\17\22\1\331\5\22\17\0\1\22\4\0"+
    "\26\22\2\0\14\22\1\332\11\22\17\0\1\22\4\0"+
    "\26\22\2\0\10\22\1\333\6\22\1\334\1\335\5\22"+
    "\17\0\1\22\4\0\26\22\2\0\20\22\1\336\5\22"+
    "\17\0\1\22\4\0\26\22\2\0\1\337\25\22\17\0"+
    "\1\22\4\0\26\22\2\0\17\22\1\340\6\22\17\0"+
    "\1\22\4\0\26\22\2\0\15\22\1\341\10\22\17\0"+
    "\1\22\4\0\26\22\2\0\1\342\25\22\17\0\1\22"+
    "\4\0\13\22\1\343\12\22\2\0\26\22\17\0\1\22"+
    "\4\0\6\22\1\344\17\22\2\0\26\22\17\0\1\22"+
    "\4\0\20\22\1\345\5\22\2\0\26\22\17\0\1\22"+
    "\4\0\1\22\1\346\24\22\2\0\26\22\17\0\1\22"+
    "\4\0\21\22\1\347\4\22\2\0\26\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\350\25\22\17\0\1\22\4\0"+
    "\25\22\1\351\2\0\26\22\17\0\1\22\4\0\26\22"+
    "\2\0\20\22\1\352\5\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\353\25\22\17\0\1\22\4\0\26\22\2\0"+
    "\1\354\25\22\17\0\1\22\4\0\26\22\2\0\20\22"+
    "\1\355\5\22\17\0\1\22\4\0\26\22\2\0\23\22"+
    "\1\356\2\22\17\0\1\22\4\0\26\22\2\0\7\22"+
    "\1\357\16\22\17\0\1\22\4\0\26\22\2\0\12\22"+
    "\1\360\13\22\17\0\1\22\4\0\26\22\2\0\15\22"+
    "\1\361\10\22\17\0\1\22\4\0\26\22\2\0\1\22"+
    "\1\362\24\22\17\0\1\22\4\0\26\22\2\0\15\22"+
    "\1\363\10\22\17\0\1\22\4\0\26\22\2\0\14\22"+
    "\1\364\11\22\17\0\1\22\4\0\26\22\2\0\20\22"+
    "\1\365\5\22\17\0\1\22\4\0\26\22\2\0\14\22"+
    "\1\366\11\22\17\0\1\22\4\0\26\22\2\0\7\22"+
    "\1\367\16\22\17\0\1\22\4\0\26\22\2\0\5\22"+
    "\1\370\3\22\1\371\14\22\17\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\372\20\22\17\0\1\22\4\0\26\22"+
    "\2\0\3\22\1\373\22\22\17\0\1\22\4\0\26\22"+
    "\2\0\20\22\1\374\5\22\17\0\1\22\4\0\26\22"+
    "\2\0\17\22\1\375\6\22\17\0\1\22\4\0\26\22"+
    "\2\0\25\22\1\376\17\0\1\22\4\0\26\22\2\0"+
    "\17\22\1\377\6\22\17\0\1\22\4\0\1\22\1\u0100"+
    "\24\22\2\0\26\22\17\0\1\22\4\0\13\22\1\u0101"+
    "\12\22\2\0\26\22\17\0\1\22\4\0\26\22\2\0"+
    "\1\u0102\25\22\17\0\1\22\4\0\21\22\1\u0103\4\22"+
    "\2\0\26\22\17\0\1\22\4\0\1\u0104\25\22\2\0"+
    "\26\22\17\0\1\22\4\0\4\22\1\u0105\21\22\2\0"+
    "\26\22\17\0\1\22\4\0\1\22\1\u0106\24\22\2\0"+
    "\26\22\17\0\1\22\4\0\26\22\2\0\16\22\1\u0107"+
    "\7\22\17\0\1\22\4\0\26\22\2\0\1\22\1\u0108"+
    "\24\22\17\0\1\22\4\0\26\22\2\0\21\22\1\u0109"+
    "\4\22\17\0\1\22\4\0\26\22\2\0\5\22\1\u010a"+
    "\20\22\17\0\1\22\4\0\26\22\2\0\1\u010b\25\22"+
    "\17\0\1\22\4\0\26\22\2\0\23\22\1\u010c\2\22"+
    "\17\0\1\22\4\0\26\22\2\0\12\22\1\u010d\13\22"+
    "\17\0\1\22\4\0\26\22\2\0\13\22\1\u010e\12\22"+
    "\17\0\1\22\4\0\26\22\2\0\21\22\1\u010f\4\22"+
    "\17\0\1\22\4\0\26\22\2\0\22\22\1\u0110\3\22"+
    "\17\0\1\22\4\0\26\22\2\0\1\22\1\u0111\24\22"+
    "\17\0\1\22\4\0\26\22\2\0\20\22\1\u0112\5\22"+
    "\17\0\1\22\4\0\26\22\2\0\20\22\1\u0113\5\22"+
    "\17\0\1\22\4\0\26\22\2\0\15\22\1\u0114\10\22"+
    "\17\0\1\22\4\0\26\22\2\0\6\22\1\u0115\17\22"+
    "\17\0\1\22\4\0\26\22\2\0\15\22\1\u0116\10\22"+
    "\17\0\1\22\4\0\26\22\2\0\1\u0117\25\22\17\0"+
    "\1\22\4\0\26\22\2\0\1\u0118\25\22\17\0\1\22"+
    "\4\0\16\22\1\u0119\7\22\2\0\26\22\17\0\1\22"+
    "\4\0\17\22\1\u011a\6\22\2\0\26\22\17\0\1\22"+
    "\4\0\17\22\1\u011b\6\22\2\0\26\22\17\0\1\22"+
    "\4\0\17\22\1\u011c\6\22\2\0\26\22\17\0\1\22"+
    "\4\0\13\22\1\u011d\12\22\2\0\26\22\17\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\u011e\10\22\17\0\1\22"+
    "\4\0\26\22\2\0\3\22\1\u011f\22\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\u0120\25\22\17\0\1\22\4\0"+
    "\26\22\2\0\20\22\1\u0121\5\22\17\0\1\22\4\0"+
    "\26\22\2\0\16\22\1\u0122\7\22\17\0\1\22\4\0"+
    "\26\22\2\0\5\22\1\u0123\20\22\17\0\1\22\4\0"+
    "\26\22\2\0\21\22\1\u0124\4\22\17\0\1\22\4\0"+
    "\26\22\2\0\2\22\1\u0125\23\22\17\0\1\22\4\0"+
    "\26\22\2\0\1\u0126\25\22\17\0\1\22\4\0\26\22"+
    "\2\0\13\22\1\u0127\12\22\17\0\1\22\4\0\26\22"+
    "\2\0\12\22\1\u0128\13\22\17\0\1\22\4\0\26\22"+
    "\2\0\21\22\1\u0129\4\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\u012a\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\17\22\1\u012b\6\22\17\0\1\22\4\0\26\22"+
    "\2\0\22\22\1\u012c\3\22\17\0\1\22\4\0\26\22"+
    "\2\0\22\22\1\u012d\3\22\17\0\1\22\4\0\26\22"+
    "\2\0\2\22\1\u012e\23\22\17\0\1\22\4\0\26\22"+
    "\2\0\3\22\1\u012f\22\22\17\0\1\22\4\0\13\22"+
    "\1\u0130\12\22\2\0\26\22\17\0\1\22\4\0\22\22"+
    "\1\u0131\3\22\2\0\26\22\17\0\1\22\4\0\10\22"+
    "\1\u0132\15\22\2\0\26\22\17\0\1\22\4\0\17\22"+
    "\1\u0133\6\22\2\0\26\22\17\0\1\22\4\0\16\22"+
    "\1\u0134\7\22\2\0\26\22\17\0\1\22\4\0\26\22"+
    "\2\0\11\22\1\u0135\14\22\17\0\1\22\4\0\26\22"+
    "\2\0\21\22\1\u0136\4\22\17\0\1\22\4\0\26\22"+
    "\2\0\14\22\1\u0137\11\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\u0138\25\22\17\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u0139\10\22\17\0\1\22\4\0\26\22\2\0"+
    "\10\22\1\u013a\15\22\17\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u013b\10\22\17\0\1\22\4\0\26\22\2\0"+
    "\10\22\1\u013c\6\22\1\u013d\1\u013e\5\22\17\0\1\22"+
    "\4\0\26\22\2\0\2\22\1\u013f\23\22\17\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\u0140\4\22\17\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\u0141\10\22\17\0\1\22"+
    "\4\0\26\22\2\0\22\22\1\u0142\3\22\17\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\u0143\20\22\17\0\1\22"+
    "\4\0\26\22\2\0\12\22\1\u0144\13\22\17\0\1\22"+
    "\4\0\26\22\2\0\14\22\1\u0145\11\22\17\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\u0146\10\22\17\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\u0147\10\22\17\0\1\22"+
    "\4\0\21\22\1\u0148\4\22\2\0\26\22\17\0\1\22"+
    "\4\0\15\22\1\u0149\10\22\2\0\26\22\17\0\1\22"+
    "\4\0\12\22\1\u014a\13\22\2\0\26\22\17\0\1\22"+
    "\4\0\10\22\1\u014b\15\22\2\0\26\22\17\0\1\22"+
    "\4\0\2\22\1\u014c\23\22\2\0\26\22\17\0\1\22"+
    "\4\0\26\22\2\0\14\22\1\u014d\11\22\17\0\1\22"+
    "\4\0\26\22\2\0\11\22\1\u014e\14\22\17\0\1\22"+
    "\4\0\26\22\2\0\1\u014f\25\22\17\0\1\22\4\0"+
    "\26\22\2\0\3\22\1\u0150\22\22\17\0\1\22\4\0"+
    "\26\22\2\0\11\22\1\u0151\14\22\17\0\1\22\4\0"+
    "\26\22\2\0\1\u0152\25\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\u0153\25\22\17\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\u0154\3\22\1\u0155\14\22\17\0\1\22\4\0"+
    "\26\22\2\0\5\22\1\u0156\20\22\17\0\1\22\4\0"+
    "\26\22\2\0\3\22\1\u0157\22\22\17\0\1\22\4\0"+
    "\26\22\2\0\5\22\1\u0158\20\22\17\0\1\22\4\0"+
    "\26\22\2\0\10\22\1\u0159\15\22\17\0\1\22\4\0"+
    "\26\22\2\0\17\22\1\u015a\6\22\17\0\1\22\4\0"+
    "\26\22\2\0\17\22\1\u015b\6\22\17\0\1\22\4\0"+
    "\26\22\2\0\1\u015c\25\22\17\0\1\22\4\0\26\22"+
    "\2\0\4\22\1\u015d\21\22\17\0\1\22\4\0\26\22"+
    "\2\0\14\22\1\u015e\11\22\17\0\1\22\4\0\26\22"+
    "\2\0\13\22\1\u015f\12\22\17\0\1\22\4\0\4\22"+
    "\1\u0160\21\22\2\0\26\22\17\0\1\22\4\0\4\22"+
    "\1\u0161\21\22\2\0\26\22\17\0\1\22\4\0\4\22"+
    "\1\u0162\21\22\2\0\26\22\17\0\1\22\4\0\12\22"+
    "\1\u0163\13\22\2\0\26\22\17\0\1\22\4\0\26\22"+
    "\2\0\21\22\1\u0164\4\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\u0165\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\13\22\1\u0166\12\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\u0167\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\14\22\1\u0168\11\22\17\0\1\22\4\0\26\22"+
    "\2\0\23\22\1\u0169\2\22\17\0\1\22\4\0\26\22"+
    "\2\0\16\22\1\u016a\7\22\17\0\1\22\4\0\26\22"+
    "\2\0\1\22\1\u016b\24\22\17\0\1\22\4\0\26\22"+
    "\2\0\20\22\1\u016c\5\22\17\0\1\22\4\0\26\22"+
    "\2\0\20\22\1\u016d\5\22\17\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\u016e\10\22\17\0\1\22\4\0\26\22"+
    "\2\0\17\22\1\u016f\6\22\17\0\1\22\4\0\26\22"+
    "\2\0\25\22\1\u0170\17\0\1\22\4\0\26\22\2\0"+
    "\3\22\1\u0171\22\22\17\0\1\22\4\0\26\22\2\0"+
    "\4\22\1\u0172\21\22\17\0\1\22\4\0\26\22\2\0"+
    "\20\22\1\u0173\5\22\17\0\1\22\4\0\26\22\2\0"+
    "\22\22\1\u0174\3\22\17\0\1\22\4\0\26\22\2\0"+
    "\2\22\1\u0175\23\22\17\0\1\22\4\0\17\22\1\u0176"+
    "\6\22\2\0\26\22\17\0\1\22\4\0\26\22\2\0"+
    "\14\22\1\u0177\11\22\17\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u0178\10\22\17\0\1\22\4\0\26\22\2\0"+
    "\22\22\1\u0179\3\22\17\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\u017a\4\22\17\0\1\22\4\0\26\22\2\0"+
    "\11\22\1\u017b\14\22\17\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u017c\10\22\17\0\1\22\4\0\26\22\2\0"+
    "\12\22\1\u017d\13\22\17\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\u017e\4\22\17\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u017f\10\22\17\0\1\22\4\0\26\22\2\0"+
    "\17\22\1\u0180\6\22\17\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\u0181\20\22\17\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\u0182\20\22\17\0\1\22\4\0\26\22\2\0"+
    "\20\22\1\u0183\5\22\17\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u0184\10\22\17\0\1\22\4\0\26\22\2\0"+
    "\1\u0185\25\22\17\0\1\22\4\0\26\22\2\0\23\22"+
    "\1\u0186\2\22\17\0\1\22\4\0\26\22\2\0\14\22"+
    "\1\u0187\11\22\17\0\1\22\4\0\26\22\2\0\3\22"+
    "\1\u0188\22\22\17\0\1\22\4\0\26\22\2\0\11\22"+
    "\1\u0189\14\22\17\0\1\22\4\0\26\22\2\0\21\22"+
    "\1\u018a\4\22\17\0\1\22\4\0\26\22\2\0\15\22"+
    "\1\u018b\10\22\17\0\1\22\4\0\26\22\2\0\22\22"+
    "\1\u018c\3\22\17\0\1\22\4\0\26\22\2\0\5\22"+
    "\1\u018d\20\22\17\0\1\22\4\0\26\22\2\0\6\22"+
    "\1\u018e\17\22\17\0\1\22\4\0\26\22\2\0\1\u018f"+
    "\25\22\17\0\1\22\4\0\26\22\2\0\16\22\1\u0190"+
    "\7\22\17\0\1\22\4\0\26\22\2\0\5\22\1\u0191"+
    "\20\22\17\0\1\22\4\0\26\22\2\0\21\22\1\u0192"+
    "\4\22\17\0\1\22\4\0\26\22\2\0\21\22\1\u0193"+
    "\4\22\17\0\1\22\4\0\26\22\2\0\14\22\1\u0194"+
    "\11\22\17\0\1\22\4\0\26\22\2\0\10\22\1\u0195"+
    "\15\22\17\0\1\22\4\0\26\22\2\0\17\22\1\u0196"+
    "\6\22\17\0\1\22\4\0\26\22\2\0\17\22\1\u0197"+
    "\6\22\17\0\1\22\4\0\26\22\2\0\5\22\1\u0198"+
    "\20\22\17\0\1\22\4\0\26\22\2\0\16\22\1\u0199"+
    "\7\22\17\0\1\22\4\0\26\22\2\0\5\22\1\u019a"+
    "\20\22\17\0\1\22\4\0\26\22\2\0\20\22\1\u019b"+
    "\5\22\17\0\1\22\4\0\26\22\2\0\15\22\1\u019c"+
    "\10\22\17\0\1\22\4\0\26\22\2\0\21\22\1\u019d"+
    "\4\22\17\0\1\22\4\0\26\22\2\0\25\22\1\u019e"+
    "\17\0\1\22\4\0\26\22\2\0\3\22\1\u019f\22\22"+
    "\17\0\1\22\4\0\26\22\2\0\14\22\1\u01a0\11\22"+
    "\17\0\1\22\4\0\26\22\2\0\15\22\1\u01a1\10\22"+
    "\17\0\1\22\4\0\26\22\2\0\14\22\1\u01a2\11\22"+
    "\17\0\1\22\4\0\26\22\2\0\17\22\1\u01a3\6\22"+
    "\17\0\1\22\4\0\26\22\2\0\20\22\1\u01a4\5\22"+
    "\17\0\1\22\4\0\26\22\2\0\5\22\1\u01a5\20\22"+
    "\17\0\1\22\4\0\26\22\2\0\20\22\1\u01a6\5\22"+
    "\17\0\1\22\4\0\26\22\2\0\11\22\1\u01a7\14\22"+
    "\17\0\1\22\4\0\26\22\2\0\1\22\1\u01a8\24\22"+
    "\17\0\1\22\4\0\26\22\2\0\25\22\1\u01a9\17\0"+
    "\1\22\4\0\26\22\2\0\5\22\1\u01aa\20\22\17\0"+
    "\1\22\4\0\26\22\2\0\14\22\1\u01ab\11\22\17\0"+
    "\1\22\4\0\26\22\2\0\12\22\1\u01ac\13\22\17\0"+
    "\1\22\4\0\26\22\2\0\21\22\1\u01ad\4\22\17\0"+
    "\1\22\4\0\26\22\2\0\21\22\1\u01ae\4\22\17\0"+
    "\1\22\4\0\26\22\2\0\20\22\1\u01af\5\22\17\0"+
    "\1\22\4\0\26\22\2\0\25\22\1\u01b0\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[24222];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\3\1\3\11\2\1\1\11\13\1\2\11"+
    "\20\1\1\11\1\1\2\11\1\1\3\11\1\1\1\0"+
    "\3\11\41\1\2\11\u0156\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[432];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Léxico: " + yytext() + " en línea " + (yyline + 1)); 
    // Aquí luego agregaremos la lógica para guardar el error en tu reporte visual
            }
          // fall through
          case 77: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 78: break;
          case 3:
            { return new Symbol(sym.NOT, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 79: break;
          case 4:
            { return new Symbol(sym.LPAREN, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 80: break;
          case 5:
            { return new Symbol(sym.RPAREN, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 81: break;
          case 6:
            { return new Symbol(sym.COMMA, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 82: break;
          case 7:
            { return new Symbol(sym.INTEGER, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 83: break;
          case 8:
            { return new Symbol(sym.COLON, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 84: break;
          case 9:
            { return new Symbol(sym.LT, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 85: break;
          case 10:
            { return new Symbol(sym.GT, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 86: break;
          case 11:
            { return new Symbol(sym.ID, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 87: break;
          case 12:
            { return new Symbol(sym.LBRACKET, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 88: break;
          case 13:
            { return new Symbol(sym.RBRACKET, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 89: break;
          case 14:
            { return new Symbol(sym.LBRACE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 90: break;
          case 15:
            { return new Symbol(sym.RBRACE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 91: break;
          case 16:
            { /* Ignorar contenido */
            }
          // fall through
          case 92: break;
          case 17:
            { return new Symbol(sym.NEQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 93: break;
          case 18:
            { return new Symbol(sym.AND, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 94: break;
          case 19:
            { yybegin(MULTILINE_COMMENT);
            }
          // fall through
          case 95: break;
          case 20:
            { return new Symbol(sym.LTEQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 96: break;
          case 21:
            { return new Symbol(sym.EQEQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 97: break;
          case 22:
            { return new Symbol(sym.GTEQ, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 98: break;
          case 23:
            { return new Symbol(sym.IF, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 99: break;
          case 24:
            { return new Symbol(sym.OR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 100: break;
          case 25:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 101: break;
          case 26:
            { return new Symbol(sym.FLOAT, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 102: break;
          case 27:
            { return new Symbol(sym.RUN, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 103: break;
          case 28:
            { return new Symbol(sym.REST, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 104: break;
          case 29:
            { return new Symbol(sym.ELSE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 105: break;
          case 30:
            { return new Symbol(sym.MAGE, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 106: break;
          case 31:
            { return new Symbol(sym.MAIN, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 107: break;
          case 32:
            { return new Symbol(sym.SEED, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 108: break;
          case 33:
            { return new Symbol(sym.THEN, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 109: break;
          case 34:
            { return new Symbol(sym.WITH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 110: break;
          case 35:
            { return new Symbol(sym.SLASH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 111: break;
          case 36:
            { return new Symbol(sym.MATCH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 112: break;
          case 37:
            { return new Symbol(sym.RULES, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 113: break;
          case 38:
            { return new Symbol(sym.RANDOM, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 114: break;
          case 39:
            { return new Symbol(sym.ROUNDS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 115: break;
          case 40:
            { return new Symbol(sym.WAR_CRY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 116: break;
          case 41:
            { return new Symbol(sym.BONUSES, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 117: break;
          case 42:
            { return new Symbol(sym.INITIAL, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 118: break;
          case 43:
            { return new Symbol(sym.PLAYERS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 119: break;
          case 44:
            { return new Symbol(sym.SCORING, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 120: break;
          case 45:
            { return new Symbol(sym.WARRIOR, yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 121: break;
          case 46:
            { return new Symbol(sym.FIREBALL, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 122: break;
          case 47:
            { return new Symbol(sym.MEDITATE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 123: break;
          case 48:
            { return new Symbol(sym.GET_MOVE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 124: break;
          case 49:
            { return new Symbol(sym.LAST_MOVE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 125: break;
          case 50:
            { return new Symbol(sym.MAGE_COMBO, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 126: break;
          case 51:
            { return new Symbol(sym.SELF_SCORE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 127: break;
          case 52:
            { return new Symbol(sym.ARCANE_BOLT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 128: break;
          case 53:
            { return new Symbol(sym.SELF_HEALTH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 129: break;
          case 54:
            { return new Symbol(sym.HEALING_RUNE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 130: break;
          case 55:
            { return new Symbol(sym.HEAVY_STRIKE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 131: break;
          case 56:
            { return new Symbol(sym.SHIELD_BLOCK, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 132: break;
          case 57:
            { return new Symbol(sym.DAMAGE_POINT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 133: break;
          case 58:
            { return new Symbol(sym.ROUND_NUMBER, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 134: break;
          case 59:
            { return new Symbol(sym.SELF_HISTORY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 135: break;
          case 60:
            { return new Symbol(sym.TOTAL_ROUNDS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 136: break;
          case 61:
            { return new Symbol(sym.MAGIC_BARRIER, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 137: break;
          case 62:
            { return new Symbol(sym.HEALING_POINT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 138: break;
          case 63:
            { return new Symbol(sym.SELF_RESOURCE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 139: break;
          case 64:
            { return new Symbol(sym.VICTORY_BONUS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 140: break;
          case 65:
            { return new Symbol(sym.WARRIOR_COMBO, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 141: break;
          case 66:
            { return new Symbol(sym.OPPONENT_SCORE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 142: break;
          case 67:
            { return new Symbol(sym.GET_MOVES_COUNT, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 143: break;
          case 68:
            { return new Symbol(sym.OPPONENT_HEALTH, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 144: break;
          case 69:
            { return new Symbol(sym.GET_LAST_N_MOVES, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 145: break;
          case 70:
            { return new Symbol(sym.OPPONENT_HISTORY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 146: break;
          case 71:
            { return new Symbol(sym.MAGE_COMBO_POINTS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 147: break;
          case 72:
            { return new Symbol(sym.OPPONENT_RESOURCE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 148: break;
          case 73:
            { return new Symbol(sym.LOW_HEALTH_VICTORY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 149: break;
          case 74:
            { return new Symbol(sym.SUCCESSFUL_DEFENSE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 150: break;
          case 75:
            { return new Symbol(sym.WARRIOR_COMBO_POINTS, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 151: break;
          case 76:
            { return new Symbol(sym.FAILED_ACTION_PENALTY, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 152: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
