
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1.analizadores;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import proyecto1.ast.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\067\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\022\017\000\002\010\003\000" +
    "\002\010\003\000\002\015\004\000\002\015\003\000\002" +
    "\014\007\000\002\013\004\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\003\000\002\011\003\000\002\020\005\000\002" +
    "\020\003\000\002\016\005\000\002\016\005\000\002\016" +
    "\004\000\002\016\005\000\002\016\005\000\002\016\005" +
    "\000\002\016\005\000\002\016\005\000\002\016\005\000" +
    "\002\016\005\000\002\017\003\000\002\017\003\000\002" +
    "\017\003\000\002\017\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\017\003\000\002\017\003\000\002\017\003\000" +
    "\002\023\102\000\002\005\006\000\002\006\004\000\002" +
    "\006\003\000\002\007\014\000\002\021\005\000\002\021" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\012\007\012\010\011\014\006\021\010\001" +
    "\002\000\014\002\ufffb\007\ufffb\010\ufffb\014\ufffb\021\ufffb" +
    "\001\002\000\014\002\ufffc\007\ufffc\010\ufffc\014\ufffc\021" +
    "\ufffc\001\002\000\004\004\144\001\002\000\014\002\ufffd" +
    "\007\ufffd\010\ufffd\014\ufffd\021\ufffd\001\002\000\004\103" +
    "\122\001\002\000\004\004\ufff8\001\002\000\004\004\ufff9" +
    "\001\002\000\004\004\021\001\002\000\004\002\020\001" +
    "\002\000\014\002\ufffe\007\ufffe\010\ufffe\014\ufffe\021\ufffe" +
    "\001\002\000\014\002\000\007\012\010\011\014\006\021" +
    "\010\001\002\000\014\002\uffff\007\uffff\010\uffff\014\uffff" +
    "\021\uffff\001\002\000\004\002\001\001\002\000\004\103" +
    "\022\001\002\000\004\025\023\001\002\000\004\111\024" +
    "\001\002\000\026\027\036\030\030\031\031\032\035\033" +
    "\034\034\026\035\032\036\037\037\027\040\025\001\002" +
    "\000\034\012\uffea\026\uffea\072\uffea\073\uffea\074\uffea\075" +
    "\uffea\076\uffea\077\uffea\100\uffea\101\uffea\106\uffea\110\uffea" +
    "\112\uffea\001\002\000\034\012\uffee\026\uffee\072\uffee\073" +
    "\uffee\074\uffee\075\uffee\076\uffee\077\uffee\100\uffee\101\uffee" +
    "\106\uffee\110\uffee\112\uffee\001\002\000\034\012\uffeb\026" +
    "\uffeb\072\uffeb\073\uffeb\074\uffeb\075\uffeb\076\uffeb\077\uffeb" +
    "\100\uffeb\101\uffeb\106\uffeb\110\uffeb\112\uffeb\001\002\000" +
    "\034\012\ufff2\026\ufff2\072\ufff2\073\ufff2\074\ufff2\075\ufff2" +
    "\076\ufff2\077\ufff2\100\ufff2\101\ufff2\106\ufff2\110\ufff2\112" +
    "\ufff2\001\002\000\034\012\ufff1\026\ufff1\072\ufff1\073\ufff1" +
    "\074\ufff1\075\ufff1\076\ufff1\077\ufff1\100\ufff1\101\ufff1\106" +
    "\ufff1\110\ufff1\112\ufff1\001\002\000\034\012\uffed\026\uffed" +
    "\072\uffed\073\uffed\074\uffed\075\uffed\076\uffed\077\uffed\100" +
    "\uffed\101\uffed\106\uffed\110\uffed\112\uffed\001\002\000\004" +
    "\026\040\001\002\000\034\012\uffef\026\uffef\072\uffef\073" +
    "\uffef\074\uffef\075\uffef\076\uffef\077\uffef\100\uffef\101\uffef" +
    "\106\uffef\110\uffef\112\uffef\001\002\000\034\012\ufff0\026" +
    "\ufff0\072\ufff0\073\ufff0\074\ufff0\075\ufff0\076\ufff0\077\ufff0" +
    "\100\ufff0\101\ufff0\106\ufff0\110\ufff0\112\ufff0\001\002\000" +
    "\034\012\ufff3\026\ufff3\072\ufff3\073\ufff3\074\ufff3\075\ufff3" +
    "\076\ufff3\077\ufff3\100\ufff3\101\ufff3\106\ufff3\110\ufff3\112" +
    "\ufff3\001\002\000\034\012\uffec\026\uffec\072\uffec\073\uffec" +
    "\074\uffec\075\uffec\076\uffec\077\uffec\100\uffec\101\uffec\106" +
    "\uffec\110\uffec\112\uffec\001\002\000\004\111\041\001\002" +
    "\000\004\105\042\001\002\000\004\011\044\001\002\000" +
    "\006\011\044\013\114\001\002\000\060\005\064\006\062" +
    "\027\036\030\030\031\031\032\035\033\034\034\026\035" +
    "\032\036\037\037\027\040\025\041\065\042\052\043\053" +
    "\044\060\045\063\046\056\047\057\050\047\053\061\102" +
    "\051\107\054\001\002\000\006\011\ufff6\013\ufff6\001\002" +
    "\000\026\012\uffd2\072\uffd2\073\uffd2\074\uffd2\075\uffd2\076" +
    "\uffd2\077\uffd2\100\uffd2\101\uffd2\110\uffd2\001\002\000\026" +
    "\012\uffd4\072\uffd4\073\uffd4\074\uffd4\075\uffd4\076\uffd4\077" +
    "\uffd4\100\uffd4\101\uffd4\110\uffd4\001\002\000\010\012\111" +
    "\100\104\101\105\001\002\000\060\005\064\006\062\027" +
    "\036\030\030\031\031\032\035\033\034\034\026\035\032" +
    "\036\037\037\027\040\025\041\065\042\052\043\053\044" +
    "\060\045\063\046\056\047\057\050\047\053\061\102\051" +
    "\107\054\001\002\000\026\012\uffda\072\uffda\073\uffda\074" +
    "\uffda\075\uffda\076\uffda\077\uffda\100\uffda\101\uffda\110\uffda" +
    "\001\002\000\026\012\uffd9\072\uffd9\073\uffd9\074\uffd9\075" +
    "\uffd9\076\uffd9\077\uffd9\100\uffd9\101\uffd9\110\uffd9\001\002" +
    "\000\060\005\064\006\062\027\036\030\030\031\031\032" +
    "\035\033\034\034\026\035\032\036\037\037\027\040\025" +
    "\041\065\042\052\043\053\044\060\045\063\046\056\047" +
    "\057\050\047\053\061\102\051\107\054\001\002\000\016" +
    "\072\072\073\071\074\073\075\070\076\066\077\067\001" +
    "\002\000\026\012\uffd6\072\uffd6\073\uffd6\074\uffd6\075\uffd6" +
    "\076\uffd6\077\uffd6\100\uffd6\101\uffd6\110\uffd6\001\002\000" +
    "\026\012\uffd5\072\uffd5\073\uffd5\074\uffd5\075\uffd5\076\uffd5" +
    "\077\uffd5\100\uffd5\101\uffd5\110\uffd5\001\002\000\026\012" +
    "\uffd8\072\uffd8\073\uffd8\074\uffd8\075\uffd8\076\uffd8\077\uffd8" +
    "\100\uffd8\101\uffd8\110\uffd8\001\002\000\026\012\uffd3\072" +
    "\uffd3\073\uffd3\074\uffd3\075\uffd3\076\uffd3\077\uffd3\100\uffd3" +
    "\101\uffd3\110\uffd3\001\002\000\026\012\uffdc\072\uffdc\073" +
    "\uffdc\074\uffdc\075\uffdc\076\uffdc\077\uffdc\100\uffdc\101\uffdc" +
    "\110\uffdc\001\002\000\026\012\uffd7\072\uffd7\073\uffd7\074" +
    "\uffd7\075\uffd7\076\uffd7\077\uffd7\100\uffd7\101\uffd7\110\uffd7" +
    "\001\002\000\026\012\uffdd\072\uffdd\073\uffdd\074\uffdd\075" +
    "\uffdd\076\uffdd\077\uffdd\100\uffdd\101\uffdd\110\uffdd\001\002" +
    "\000\026\012\uffdb\072\uffdb\073\uffdb\074\uffdb\075\uffdb\076" +
    "\uffdb\077\uffdb\100\uffdb\101\uffdb\110\uffdb\001\002\000\054" +
    "\005\064\006\062\027\036\030\030\031\031\032\035\033" +
    "\034\034\026\035\032\036\037\037\027\040\025\041\065" +
    "\042\052\043\053\044\060\045\063\046\056\047\057\050" +
    "\047\053\061\001\002\000\054\005\064\006\062\027\036" +
    "\030\030\031\031\032\035\033\034\034\026\035\032\036" +
    "\037\037\027\040\025\041\065\042\052\043\053\044\060" +
    "\045\063\046\056\047\057\050\047\053\061\001\002\000" +
    "\054\005\064\006\062\027\036\030\030\031\031\032\035" +
    "\033\034\034\026\035\032\036\037\037\027\040\025\041" +
    "\065\042\052\043\053\044\060\045\063\046\056\047\057" +
    "\050\047\053\061\001\002\000\054\005\064\006\062\027" +
    "\036\030\030\031\031\032\035\033\034\034\026\035\032" +
    "\036\037\037\027\040\025\041\065\042\052\043\053\044" +
    "\060\045\063\046\056\047\057\050\047\053\061\001\002" +
    "\000\054\005\064\006\062\027\036\030\030\031\031\032" +
    "\035\033\034\034\026\035\032\036\037\037\027\040\025" +
    "\041\065\042\052\043\053\044\060\045\063\046\056\047" +
    "\057\050\047\053\061\001\002\000\054\005\064\006\062" +
    "\027\036\030\030\031\031\032\035\033\034\034\026\035" +
    "\032\036\037\037\027\040\025\041\065\042\052\043\053" +
    "\044\060\045\063\046\056\047\057\050\047\053\061\001" +
    "\002\000\012\012\uffdf\100\uffdf\101\uffdf\110\uffdf\001\002" +
    "\000\012\012\uffe3\100\uffe3\101\uffe3\110\uffe3\001\002\000" +
    "\012\012\uffe2\100\uffe2\101\uffe2\110\uffe2\001\002\000\012" +
    "\012\uffde\100\uffde\101\uffde\110\uffde\001\002\000\012\012" +
    "\uffe0\100\uffe0\101\uffe0\110\uffe0\001\002\000\012\012\uffe1" +
    "\100\uffe1\101\uffe1\110\uffe1\001\002\000\010\100\104\101" +
    "\105\110\103\001\002\000\012\012\uffe4\100\uffe4\101\uffe4" +
    "\110\uffe4\001\002\000\060\005\064\006\062\027\036\030" +
    "\030\031\031\032\035\033\034\034\026\035\032\036\037" +
    "\037\027\040\025\041\065\042\052\043\053\044\060\045" +
    "\063\046\056\047\057\050\047\053\061\102\051\107\054" +
    "\001\002\000\060\005\064\006\062\027\036\030\030\031" +
    "\031\032\035\033\034\034\026\035\032\036\037\037\027" +
    "\040\025\041\065\042\052\043\053\044\060\045\063\046" +
    "\056\047\057\050\047\053\061\102\051\107\054\001\002" +
    "\000\012\012\uffe7\100\104\101\uffe7\110\uffe7\001\002\000" +
    "\012\012\uffe6\100\uffe6\101\uffe6\110\uffe6\001\002\000\012" +
    "\012\uffe5\100\uffe5\101\uffe5\110\uffe5\001\002\000\026\027" +
    "\036\030\030\031\031\032\035\033\034\034\026\035\032" +
    "\036\037\037\027\040\025\001\002\000\004\112\113\001" +
    "\002\000\006\011\ufff5\013\ufff5\001\002\000\026\027\036" +
    "\030\030\031\031\032\035\033\034\034\026\035\032\036" +
    "\037\037\027\040\025\001\002\000\004\106\117\001\002" +
    "\000\006\011\ufff7\013\ufff7\001\002\000\004\104\120\001" +
    "\002\000\014\002\ufffa\007\ufffa\010\ufffa\014\ufffa\021\ufffa" +
    "\001\002\000\004\106\ufff4\001\002\000\004\022\124\001" +
    "\002\000\006\022\uffce\104\uffce\001\002\000\004\105\130" +
    "\001\002\000\006\022\124\104\127\001\002\000\006\022" +
    "\uffcf\104\uffcf\001\002\000\014\002\uffd0\007\uffd0\010\uffd0" +
    "\014\uffd0\021\uffd0\001\002\000\004\004\131\001\002\000" +
    "\006\106\uffcb\112\uffcb\001\002\000\006\106\134\112\133" +
    "\001\002\000\004\004\143\001\002\000\004\023\135\001" +
    "\002\000\004\103\136\001\002\000\004\024\137\001\002" +
    "\000\004\111\140\001\002\000\004\005\141\001\002\000" +
    "\004\104\142\001\002\000\006\022\uffcd\104\uffcd\001\002" +
    "\000\006\106\uffcc\112\uffcc\001\002\000\004\103\145\001" +
    "\002\000\004\015\146\001\002\000\004\111\147\001\002" +
    "\000\004\105\150\001\002\000\004\004\151\001\002\000" +
    "\004\112\152\001\002\000\004\004\153\001\002\000\004" +
    "\106\154\001\002\000\004\016\155\001\002\000\004\111" +
    "\156\001\002\000\004\005\157\001\002\000\004\017\160" +
    "\001\002\000\004\111\161\001\002\000\004\103\162\001" +
    "\002\000\004\060\163\001\002\000\004\111\164\001\002" +
    "\000\004\005\165\001\002\000\004\112\166\001\002\000" +
    "\004\061\167\001\002\000\004\111\170\001\002\000\004" +
    "\005\171\001\002\000\004\112\172\001\002\000\004\062" +
    "\173\001\002\000\004\111\174\001\002\000\004\005\175" +
    "\001\002\000\004\112\176\001\002\000\004\063\177\001" +
    "\002\000\004\111\200\001\002\000\004\005\201\001\002" +
    "\000\004\112\202\001\002\000\004\064\203\001\002\000" +
    "\004\111\204\001\002\000\004\005\205\001\002\000\004" +
    "\104\206\001\002\000\004\020\207\001\002\000\004\111" +
    "\210\001\002\000\004\103\211\001\002\000\004\065\212" +
    "\001\002\000\004\111\213\001\002\000\004\105\214\001" +
    "\002\000\026\027\036\030\030\031\031\032\035\033\034" +
    "\034\026\035\032\036\037\037\027\040\025\001\002\000" +
    "\006\106\220\112\217\001\002\000\006\106\uffe8\112\uffe8" +
    "\001\002\000\026\027\036\030\030\031\031\032\035\033" +
    "\034\034\026\035\032\036\037\037\027\040\025\001\002" +
    "\000\004\112\221\001\002\000\004\066\222\001\002\000" +
    "\004\111\223\001\002\000\004\005\224\001\002\000\004" +
    "\112\225\001\002\000\004\067\226\001\002\000\004\111" +
    "\227\001\002\000\004\105\230\001\002\000\026\027\036" +
    "\030\030\031\031\032\035\033\034\034\026\035\032\036" +
    "\037\037\027\040\025\001\002\000\006\106\232\112\217" +
    "\001\002\000\004\112\233\001\002\000\004\070\234\001" +
    "\002\000\004\111\235\001\002\000\004\005\236\001\002" +
    "\000\004\112\237\001\002\000\004\071\240\001\002\000" +
    "\004\111\241\001\002\000\004\005\242\001\002\000\004" +
    "\104\243\001\002\000\004\104\244\001\002\000\014\002" +
    "\uffd1\007\uffd1\010\uffd1\014\uffd1\021\uffd1\001\002\000\006" +
    "\106\uffe9\112\uffe9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\020\002\013\003\015\004\014\005\003\010" +
    "\012\022\006\023\004\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\004\016\005" +
    "\003\010\012\022\006\023\004\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\032\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\044" +
    "\015\042\001\001\000\006\013\114\014\115\001\001\000" +
    "\010\011\045\016\047\017\054\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\011\045\016\107\017\054\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\011\045\016\101\017\054\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\045\017\100\001\001\000\006\011\045\017\077\001" +
    "\001\000\006\011\045\017\076\001\001\000\006\011\045" +
    "\017\075\001\001\000\006\011\045\017\074\001\001\000" +
    "\006\011\045\017\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\011\045\016\106\017\054\001\001\000\010\011" +
    "\045\016\105\017\054\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\111\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\120\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\006\124\007\122" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\125\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\011\215\020\214\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\244\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\215\020\230\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    //GUARDAR OBJETOS VIVOS 
    public ArrayList<Estrategia> estrategiasAST = new ArrayList<>();
    public ArrayList<Partida> partidasAST = new ArrayList<>();
    public ArrayList<String> partidasAEjecutar = new ArrayList<>();
    public int semillaSimulacion = 0;

    public java.util.ArrayList<ErrorInfo> listaErroresSintacticos = new java.util.ArrayList<>();

    public void syntax_error(Symbol s) {
        String lexema = (s.value != null) ? s.value.toString() : "Fin de archivo";
        listaErroresSintacticos.add(new ErrorInfo("Sintáctico", "No se esperaba: " + lexema, s.left, s.right));
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        String lexema = (s.value != null) ? s.value.toString() : "Fin de archivo";
        listaErroresSintacticos.add(new ErrorInfo("Sintáctico", "Error fatal cerca de: " + lexema, s.left, s.right));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= lista_instrucciones 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_instrucciones ::= lista_instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= estrategia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= partida 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= bloque_main 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // estrategia ::= tipo_jugador ID LBRACE INITIAL COLON accion RULES COLON LBRACKET lista_reglas regla_else RBRACKET RBRACE 
            {
              Estrategia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).right;
		TipoJugador t = (TipoJugador)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-12)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-11)).value;
		int aileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int airight = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Accion ai = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int lrleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lrright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		List<Regla> lr = (List<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Accion re = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 
                  Estrategia e = new Estrategia(id, t, ai, lr, re);
                  estrategiasAST.add(e); // Guardamos la estrategia viva
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // tipo_jugador ::= MAGE 
            {
              TipoJugador RESULT =null;
		 RESULT = TipoJugador.MAGE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_jugador",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo_jugador ::= WARRIOR 
            {
              TipoJugador RESULT =null;
		 RESULT = TipoJugador.WARRIOR; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_jugador",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_reglas ::= lista_reglas regla 
            {
              List<Regla> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<Regla> l = (List<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Regla r = (Regla)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 l.add(r); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_reglas ::= regla 
            {
              List<Regla> RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Regla r = (Regla)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<Regla> l = new ArrayList<>(); l.add(r); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // regla ::= IF condicion THEN accion COMMA 
            {
              Regla RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Regla(c, a); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // regla_else ::= ELSE accion 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_else",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // accion ::= ARCANE_BOLT 
            {
              Accion RESULT =null;
		 RESULT = Accion.ARCANE_BOLT; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // accion ::= FIREBALL 
            {
              Accion RESULT =null;
		 RESULT = Accion.FIREBALL; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accion ::= MAGIC_BARRIER 
            {
              Accion RESULT =null;
		 RESULT = Accion.MAGIC_BARRIER; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // accion ::= HEALING_RUNE 
            {
              Accion RESULT =null;
		 RESULT = Accion.HEALING_RUNE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // accion ::= MEDITATE 
            {
              Accion RESULT =null;
		 RESULT = Accion.MEDITATE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // accion ::= SLASH 
            {
              Accion RESULT =null;
		 RESULT = Accion.SLASH; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // accion ::= HEAVY_STRIKE 
            {
              Accion RESULT =null;
		 RESULT = Accion.HEAVY_STRIKE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // accion ::= SHIELD_BLOCK 
            {
              Accion RESULT =null;
		 RESULT = Accion.SHIELD_BLOCK; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // accion ::= WAR_CRY 
            {
              Accion RESULT =null;
		 RESULT = Accion.WAR_CRY; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // accion ::= REST 
            {
              Accion RESULT =null;
		 RESULT = Accion.REST; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lista_acciones_secuencia ::= lista_acciones_secuencia COMMA accion 
            {
              List<Accion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<Accion> l = (List<Accion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 l.add(a); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones_secuencia",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_acciones_secuencia ::= accion 
            {
              List<Accion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<Accion> l = new ArrayList<>(); l.add(a); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones_secuencia",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= condicion OR condicion 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Condicion i = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condicion d = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionLogica(i, "OR", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= condicion AND condicion 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Condicion i = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condicion d = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionLogica(i, "AND", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion ::= NOT condicion 
            {
              Condicion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionLogica(c, "NOT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condicion ::= LPAREN condicion RPAREN 
            {
              Condicion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condicion ::= operando EQEQ operando 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionRelacional(i, "==", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condicion ::= operando NEQ operando 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionRelacional(i, "!=", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicion ::= operando LT operando 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionRelacional(i, "<", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion ::= operando GT operando 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionRelacional(i, ">", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= operando LTEQ operando 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionRelacional(i, "<=", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= operando GTEQ operando 
            {
              Condicion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new OperacionRelacional(i, ">=", d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // operando ::= INTEGER 
            {
              Expresion RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Literal(Integer.parseInt(v)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // operando ::= FLOAT 
            {
              Expresion RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Literal(Double.parseDouble(v)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // operando ::= ROUND_NUMBER 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.ROUND_NUMBER); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // operando ::= TOTAL_ROUNDS 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.TOTAL_ROUNDS); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // operando ::= SELF_HEALTH 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.SELF_HEALTH); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // operando ::= OPPONENT_HEALTH 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.OPPONENT_HEALTH); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // operando ::= SELF_RESOURCE 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.SELF_RESOURCE); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // operando ::= OPPONENT_RESOURCE 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.OPPONENT_RESOURCE); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // operando ::= SELF_SCORE 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.SELF_SCORE); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operando ::= OPPONENT_SCORE 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.OPPONENT_SCORE); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // operando ::= RANDOM 
            {
              Expresion RESULT =null;
		 RESULT = new Variable(Variable.TipoVar.RANDOM); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // operando ::= accion 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Literal(a); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // partida ::= MATCH ID LBRACE PLAYERS COLON LBRACKET ID COMMA ID RBRACKET ROUNDS COLON INTEGER SCORING COLON LBRACE DAMAGE_POINT COLON INTEGER COMMA HEALING_POINT COLON INTEGER COMMA SUCCESSFUL_DEFENSE COLON INTEGER COMMA VICTORY_BONUS COLON INTEGER COMMA FAILED_ACTION_PENALTY COLON INTEGER RBRACE BONUSES COLON LBRACE MAGE_COMBO COLON LBRACKET lista_acciones_secuencia RBRACKET COMMA MAGE_COMBO_POINTS COLON INTEGER COMMA WARRIOR_COMBO COLON LBRACKET lista_acciones_secuencia RBRACKET COMMA WARRIOR_COMBO_POINTS COLON INTEGER COMMA LOW_HEALTH_VICTORY COLON INTEGER RBRACE RBRACE 
            {
              Partida RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-62)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-62)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-62)).value;
		int p1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-57)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-57)).right;
		String p1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-57)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-55)).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-55)).right;
		String p2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-55)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-51)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-51)).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-51)).value;
		int dpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-45)).left;
		int dpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-45)).right;
		String dp = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-45)).value;
		int hpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-41)).left;
		int hpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-41)).right;
		String hp = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-41)).value;
		int defleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-37)).left;
		int defright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-37)).right;
		String def = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-37)).value;
		int vbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-33)).left;
		int vbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-33)).right;
		String vb = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-33)).value;
		int penleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-29)).left;
		int penright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-29)).right;
		String pen = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-29)).value;
		int mcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-21)).left;
		int mcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-21)).right;
		List<Accion> mc = (List<Accion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-21)).value;
		int mpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)).left;
		int mpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)).right;
		String mp = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-16)).value;
		int wcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).left;
		int wcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).right;
		List<Accion> wc = (List<Accion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-11)).value;
		int wpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int wpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String wp = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int lhvleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lhvright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String lhv = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 
               Partida p = new Partida(id, p1, p2, Integer.parseInt(r),
                           Integer.parseInt(dp), Integer.parseInt(hp), Integer.parseInt(def),
                           Integer.parseInt(vb), Integer.parseInt(pen),
                           mc, Integer.parseInt(mp), wc, Integer.parseInt(wp), Integer.parseInt(lhv));
               partidasAST.add(p);
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("partida",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-63)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // bloque_main ::= MAIN LBRACE lista_run RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_main",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // lista_run ::= lista_run instruccion_run 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // lista_run ::= instruccion_run 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // instruccion_run ::= RUN LBRACKET lista_id_partidas RBRACKET WITH LBRACE SEED COLON INTEGER RBRACE 
            {
              Object RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		List<String> lista = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
                       partidasAEjecutar.addAll(lista);
                       semillaSimulacion = Integer.parseInt(s); 
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_run",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // lista_id_partidas ::= lista_id_partidas COMMA ID 
            {
              List<String> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<String> l = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 l.add(id); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_id_partidas",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // lista_id_partidas ::= ID 
            {
              List<String> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<String> l = new ArrayList<>(); l.add(id); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_id_partidas",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
