
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1.analizadores;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\010\000\002\006\003\000" +
    "\002\006\003\000\002\007\005\000\002\010\010\000\002" +
    "\011\004\000\002\011\003\000\002\012\007\000\002\013" +
    "\004\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\015\005\000\002\015\005\000\002\015" +
    "\004\000\002\015\005\000\002\015\005\000\002\015\005" +
    "\000\002\015\005\000\002\015\005\000\002\015\005\000" +
    "\002\015\005\000\002\016\003\000\002\016\003\000\002" +
    "\016\003\000\002\016\003\000\002\016\003\000\002\016" +
    "\003\000\002\016\003\000\002\016\003\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003\000\002\016\005\000\002\017\010\000\002" +
    "\017\006\000\002\017\010\000\002\017\010\000\002\017" +
    "\010\000\002\020\003\000\002\020\003\000\002\021\005" +
    "\000\002\021\003\000\002\022\032\000\002\023\025\000" +
    "\002\024\031\000\002\025\006\000\002\026\004\000\002" +
    "\026\003\000\002\027\014\000\002\030\005\000\002\030" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\307\000\012\007\012\010\011\014\006\021\010\001" +
    "\002\000\014\002\ufffb\007\ufffb\010\ufffb\014\ufffb\021\ufffb" +
    "\001\002\000\014\002\ufffc\007\ufffc\010\ufffc\014\ufffc\021" +
    "\ufffc\001\002\000\004\004\211\001\002\000\014\002\ufffd" +
    "\007\ufffd\010\ufffd\014\ufffd\021\ufffd\001\002\000\004\103" +
    "\167\001\002\000\004\004\ufff8\001\002\000\004\004\ufff9" +
    "\001\002\000\004\004\021\001\002\000\004\002\020\001" +
    "\002\000\014\002\ufffe\007\ufffe\010\ufffe\014\ufffe\021\ufffe" +
    "\001\002\000\014\002\000\007\012\010\011\014\006\021" +
    "\010\001\002\000\014\002\uffff\007\uffff\010\uffff\014\uffff" +
    "\021\uffff\001\002\000\004\002\001\001\002\000\004\103" +
    "\022\001\002\000\004\025\023\001\002\000\004\111\165" +
    "\001\002\000\004\026\026\001\002\000\004\104\164\001" +
    "\002\000\004\111\027\001\002\000\004\105\030\001\002" +
    "\000\004\011\032\001\002\000\006\011\032\013\157\001" +
    "\002\000\072\005\070\006\064\027\036\030\044\031\057" +
    "\032\067\033\050\034\041\035\073\036\066\037\062\040" +
    "\071\041\072\042\047\043\046\044\061\045\065\046\056" +
    "\047\060\050\037\053\063\054\045\055\055\056\052\057" +
    "\035\102\043\105\051\107\053\001\002\000\006\011\ufff4" +
    "\013\ufff4\001\002\000\026\012\uffd2\072\uffd2\073\uffd2\074" +
    "\uffd2\075\uffd2\076\uffd2\077\uffd2\100\uffd2\101\uffd2\110\uffd2" +
    "\001\002\000\004\107\152\001\002\000\034\012\ufff1\026" +
    "\ufff1\072\ufff1\073\ufff1\074\ufff1\075\ufff1\076\ufff1\077\ufff1" +
    "\100\ufff1\101\ufff1\106\ufff1\110\ufff1\112\ufff1\001\002\000" +
    "\026\012\uffd4\072\uffd4\073\uffd4\074\uffd4\075\uffd4\076\uffd4" +
    "\077\uffd4\100\uffd4\101\uffd4\110\uffd4\001\002\000\026\012" +
    "\uffd1\072\uffd1\073\uffd1\074\uffd1\075\uffd1\076\uffd1\077\uffd1" +
    "\100\uffd1\101\uffd1\110\uffd1\001\002\000\034\012\uffec\026" +
    "\uffec\072\uffec\073\uffec\074\uffec\075\uffec\076\uffec\077\uffec" +
    "\100\uffec\101\uffec\106\uffec\110\uffec\112\uffec\001\002\000" +
    "\010\012\147\100\117\101\120\001\002\000\072\005\070" +
    "\006\064\027\036\030\044\031\057\032\067\033\050\034" +
    "\041\035\073\036\066\037\062\040\071\041\072\042\047" +
    "\043\046\044\061\045\065\046\056\047\060\050\037\053" +
    "\063\054\045\055\055\056\052\057\035\102\043\105\051" +
    "\107\053\001\002\000\034\012\ufff0\026\ufff0\072\ufff0\073" +
    "\ufff0\074\ufff0\075\ufff0\076\ufff0\077\ufff0\100\ufff0\101\ufff0" +
    "\106\ufff0\110\ufff0\112\ufff0\001\002\000\004\107\141\001" +
    "\002\000\026\012\uffd9\072\uffd9\073\uffd9\074\uffd9\075\uffd9" +
    "\076\uffd9\077\uffd9\100\uffd9\101\uffd9\110\uffd9\001\002\000" +
    "\026\012\uffda\072\uffda\073\uffda\074\uffda\075\uffda\076\uffda" +
    "\077\uffda\100\uffda\101\uffda\110\uffda\001\002\000\034\012" +
    "\uffed\026\uffed\072\uffed\073\uffed\074\uffed\075\uffed\076\uffed" +
    "\077\uffed\100\uffed\101\uffed\106\uffed\110\uffed\112\uffed\001" +
    "\002\000\026\027\036\030\044\031\057\032\067\033\050" +
    "\034\041\035\073\036\066\037\062\040\071\001\002\000" +
    "\004\107\123\001\002\000\072\005\070\006\064\027\036" +
    "\030\044\031\057\032\067\033\050\034\041\035\073\036" +
    "\066\037\062\040\071\041\072\042\047\043\046\044\061" +
    "\045\065\046\056\047\060\050\037\053\063\054\045\055" +
    "\055\056\052\057\035\102\043\105\051\107\053\001\002" +
    "\000\016\072\105\073\104\074\106\075\103\076\101\077" +
    "\102\001\002\000\004\107\074\001\002\000\026\012\uffd6" +
    "\072\uffd6\073\uffd6\074\uffd6\075\uffd6\076\uffd6\077\uffd6\100" +
    "\uffd6\101\uffd6\110\uffd6\001\002\000\034\012\uffef\026\uffef" +
    "\072\uffef\073\uffef\074\uffef\075\uffef\076\uffef\077\uffef\100" +
    "\uffef\101\uffef\106\uffef\110\uffef\112\uffef\001\002\000\026" +
    "\012\uffd5\072\uffd5\073\uffd5\074\uffd5\075\uffd5\076\uffd5\077" +
    "\uffd5\100\uffd5\101\uffd5\110\uffd5\001\002\000\026\012\uffd8" +
    "\072\uffd8\073\uffd8\074\uffd8\075\uffd8\076\uffd8\077\uffd8\100" +
    "\uffd8\101\uffd8\110\uffd8\001\002\000\034\012\uffe9\026\uffe9" +
    "\072\uffe9\073\uffe9\074\uffe9\075\uffe9\076\uffe9\077\uffe9\100" +
    "\uffe9\101\uffe9\106\uffe9\110\uffe9\112\uffe9\001\002\000\026" +
    "\012\uffd3\072\uffd3\073\uffd3\074\uffd3\075\uffd3\076\uffd3\077" +
    "\uffd3\100\uffd3\101\uffd3\110\uffd3\001\002\000\026\012\uffdc" +
    "\072\uffdc\073\uffdc\074\uffdc\075\uffdc\076\uffdc\077\uffdc\100" +
    "\uffdc\101\uffdc\110\uffdc\001\002\000\026\012\uffd7\072\uffd7" +
    "\073\uffd7\074\uffd7\075\uffd7\076\uffd7\077\uffd7\100\uffd7\101" +
    "\uffd7\110\uffd7\001\002\000\034\012\uffea\026\uffea\072\uffea" +
    "\073\uffea\074\uffea\075\uffea\076\uffea\077\uffea\100\uffea\101" +
    "\uffea\106\uffea\110\uffea\112\uffea\001\002\000\034\012\uffee" +
    "\026\uffee\072\uffee\073\uffee\074\uffee\075\uffee\076\uffee\077" +
    "\uffee\100\uffee\101\uffee\106\uffee\110\uffee\112\uffee\001\002" +
    "\000\026\012\uffdd\072\uffdd\073\uffdd\074\uffdd\075\uffdd\076" +
    "\uffdd\077\uffdd\100\uffdd\101\uffdd\110\uffdd\001\002\000\034" +
    "\012\uffe8\026\uffe8\072\uffe8\073\uffe8\074\uffe8\075\uffe8\076" +
    "\uffe8\077\uffe8\100\uffe8\101\uffe8\106\uffe8\110\uffe8\112\uffe8" +
    "\001\002\000\026\012\uffdb\072\uffdb\073\uffdb\074\uffdb\075" +
    "\uffdb\076\uffdb\077\uffdb\100\uffdb\101\uffdb\110\uffdb\001\002" +
    "\000\034\012\uffeb\026\uffeb\072\uffeb\073\uffeb\074\uffeb\075" +
    "\uffeb\076\uffeb\077\uffeb\100\uffeb\101\uffeb\106\uffeb\110\uffeb" +
    "\112\uffeb\001\002\000\006\051\076\052\077\001\002\000" +
    "\004\110\100\001\002\000\006\110\uffca\112\uffca\001\002" +
    "\000\006\110\uffc9\112\uffc9\001\002\000\030\012\uffce\072" +
    "\uffce\073\uffce\074\uffce\075\uffce\076\uffce\077\uffce\100\uffce" +
    "\101\uffce\110\uffce\112\uffce\001\002\000\066\005\070\006" +
    "\064\027\036\030\044\031\057\032\067\033\050\034\041" +
    "\035\073\036\066\037\062\040\071\041\072\042\047\043" +
    "\046\044\061\045\065\046\056\047\060\050\037\053\063" +
    "\054\045\055\055\056\052\057\035\105\051\001\002\000" +
    "\066\005\070\006\064\027\036\030\044\031\057\032\067" +
    "\033\050\034\041\035\073\036\066\037\062\040\071\041" +
    "\072\042\047\043\046\044\061\045\065\046\056\047\060" +
    "\050\037\053\063\054\045\055\055\056\052\057\035\105" +
    "\051\001\002\000\066\005\070\006\064\027\036\030\044" +
    "\031\057\032\067\033\050\034\041\035\073\036\066\037" +
    "\062\040\071\041\072\042\047\043\046\044\061\045\065" +
    "\046\056\047\060\050\037\053\063\054\045\055\055\056" +
    "\052\057\035\105\051\001\002\000\066\005\070\006\064" +
    "\027\036\030\044\031\057\032\067\033\050\034\041\035" +
    "\073\036\066\037\062\040\071\041\072\042\047\043\046" +
    "\044\061\045\065\046\056\047\060\050\037\053\063\054" +
    "\045\055\055\056\052\057\035\105\051\001\002\000\066" +
    "\005\070\006\064\027\036\030\044\031\057\032\067\033" +
    "\050\034\041\035\073\036\066\037\062\040\071\041\072" +
    "\042\047\043\046\044\061\045\065\046\056\047\060\050" +
    "\037\053\063\054\045\055\055\056\052\057\035\105\051" +
    "\001\002\000\066\005\070\006\064\027\036\030\044\031" +
    "\057\032\067\033\050\034\041\035\073\036\066\037\062" +
    "\040\071\041\072\042\047\043\046\044\061\045\065\046" +
    "\056\047\060\050\037\053\063\054\045\055\055\056\052" +
    "\057\035\105\051\001\002\000\012\012\uffdf\100\uffdf\101" +
    "\uffdf\110\uffdf\001\002\000\012\012\uffe3\100\uffe3\101\uffe3" +
    "\110\uffe3\001\002\000\012\012\uffe2\100\uffe2\101\uffe2\110" +
    "\uffe2\001\002\000\012\012\uffde\100\uffde\101\uffde\110\uffde" +
    "\001\002\000\012\012\uffe0\100\uffe0\101\uffe0\110\uffe0\001" +
    "\002\000\012\012\uffe1\100\uffe1\101\uffe1\110\uffe1\001\002" +
    "\000\010\100\117\101\120\110\116\001\002\000\012\012" +
    "\uffe4\100\uffe4\101\uffe4\110\uffe4\001\002\000\072\005\070" +
    "\006\064\027\036\030\044\031\057\032\067\033\050\034" +
    "\041\035\073\036\066\037\062\040\071\041\072\042\047" +
    "\043\046\044\061\045\065\046\056\047\060\050\037\053" +
    "\063\054\045\055\055\056\052\057\035\102\043\105\051" +
    "\107\053\001\002\000\072\005\070\006\064\027\036\030" +
    "\044\031\057\032\067\033\050\034\041\035\073\036\066" +
    "\037\062\040\071\041\072\042\047\043\046\044\061\045" +
    "\065\046\056\047\060\050\037\053\063\054\045\055\055" +
    "\056\052\057\035\102\043\105\051\107\053\001\002\000" +
    "\012\012\uffe7\100\117\101\uffe7\110\uffe7\001\002\000\012" +
    "\012\uffe6\100\uffe6\101\uffe6\110\uffe6\001\002\000\016\051" +
    "\076\052\077\054\045\055\055\056\052\057\035\001\002" +
    "\000\004\112\131\001\002\000\004\112\126\001\002\000" +
    "\026\027\036\030\044\031\057\032\067\033\050\034\041" +
    "\035\073\036\066\037\062\040\071\001\002\000\004\110" +
    "\130\001\002\000\030\012\uffcc\072\uffcc\073\uffcc\074\uffcc" +
    "\075\uffcc\076\uffcc\077\uffcc\100\uffcc\101\uffcc\110\uffcc\112" +
    "\uffcc\001\002\000\026\027\036\030\044\031\057\032\067" +
    "\033\050\034\041\035\073\036\066\037\062\040\071\001" +
    "\002\000\004\110\133\001\002\000\030\012\uffcd\072\uffcd" +
    "\073\uffcd\074\uffcd\075\uffcd\076\uffcd\077\uffcd\100\uffcd\101" +
    "\uffcd\110\uffcd\112\uffcd\001\002\000\006\106\137\112\136" +
    "\001\002\000\006\106\uffc7\112\uffc7\001\002\000\026\027" +
    "\036\030\044\031\057\032\067\033\050\034\041\035\073" +
    "\036\066\037\062\040\071\001\002\000\026\012\uffd0\072" +
    "\uffd0\073\uffd0\074\uffd0\075\uffd0\076\uffd0\077\uffd0\100\uffd0" +
    "\101\uffd0\110\uffd0\001\002\000\006\106\uffc8\112\uffc8\001" +
    "\002\000\006\051\076\052\077\001\002\000\004\112\143" +
    "\001\002\000\004\005\144\001\002\000\004\110\145\001" +
    "\002\000\030\012\uffcf\072\uffcf\073\uffcf\074\uffcf\075\uffcf" +
    "\076\uffcf\077\uffcf\100\uffcf\101\uffcf\110\uffcf\112\uffcf\001" +
    "\002\000\012\012\uffe5\100\uffe5\101\uffe5\110\uffe5\001\002" +
    "\000\026\027\036\030\044\031\057\032\067\033\050\034" +
    "\041\035\073\036\066\037\062\040\071\001\002\000\004" +
    "\112\151\001\002\000\006\011\ufff3\013\ufff3\001\002\000" +
    "\006\051\076\052\077\001\002\000\004\112\154\001\002" +
    "\000\004\005\155\001\002\000\004\110\156\001\002\000" +
    "\030\012\uffcb\072\uffcb\073\uffcb\074\uffcb\075\uffcb\076\uffcb" +
    "\077\uffcb\100\uffcb\101\uffcb\110\uffcb\112\uffcb\001\002\000" +
    "\026\027\036\030\044\031\057\032\067\033\050\034\041" +
    "\035\073\036\066\037\062\040\071\001\002\000\004\106" +
    "\162\001\002\000\006\011\ufff5\013\ufff5\001\002\000\004" +
    "\104\ufff6\001\002\000\004\106\ufff2\001\002\000\014\002" +
    "\ufffa\007\ufffa\010\ufffa\014\ufffa\021\ufffa\001\002\000\026" +
    "\027\036\030\044\031\057\032\067\033\050\034\041\035" +
    "\073\036\066\037\062\040\071\001\002\000\004\026\ufff7" +
    "\001\002\000\004\022\171\001\002\000\006\022\uffc1\104" +
    "\uffc1\001\002\000\004\105\175\001\002\000\006\022\171" +
    "\104\174\001\002\000\006\022\uffc2\104\uffc2\001\002\000" +
    "\014\002\uffc3\007\uffc3\010\uffc3\014\uffc3\021\uffc3\001\002" +
    "\000\004\004\176\001\002\000\006\106\uffbe\112\uffbe\001" +
    "\002\000\006\106\201\112\200\001\002\000\004\004\210" +
    "\001\002\000\004\023\202\001\002\000\004\103\203\001" +
    "\002\000\004\024\204\001\002\000\004\111\205\001\002" +
    "\000\004\005\206\001\002\000\004\104\207\001\002\000" +
    "\006\022\uffc0\104\uffc0\001\002\000\006\106\uffbf\112\uffbf" +
    "\001\002\000\004\103\212\001\002\000\004\015\213\001" +
    "\002\000\004\111\214\001\002\000\004\105\215\001\002" +
    "\000\004\004\216\001\002\000\004\112\217\001\002\000" +
    "\004\004\220\001\002\000\004\106\221\001\002\000\004" +
    "\016\222\001\002\000\004\111\223\001\002\000\004\005" +
    "\224\001\002\000\004\017\225\001\002\000\004\111\226" +
    "\001\002\000\004\103\227\001\002\000\004\060\231\001" +
    "\002\000\004\104\254\001\002\000\004\111\232\001\002" +
    "\000\004\005\233\001\002\000\004\112\234\001\002\000" +
    "\004\061\235\001\002\000\004\111\236\001\002\000\004" +
    "\005\237\001\002\000\004\112\240\001\002\000\004\062" +
    "\241\001\002\000\004\111\242\001\002\000\004\005\243" +
    "\001\002\000\004\112\244\001\002\000\004\063\245\001" +
    "\002\000\004\111\246\001\002\000\004\005\247\001\002" +
    "\000\004\112\250\001\002\000\004\064\251\001\002\000" +
    "\004\111\252\001\002\000\004\005\253\001\002\000\004" +
    "\104\uffc5\001\002\000\004\020\255\001\002\000\004\111" +
    "\256\001\002\000\004\103\257\001\002\000\004\065\260" +
    "\001\002\000\004\111\264\001\002\000\004\104\262\001" +
    "\002\000\004\104\263\001\002\000\014\002\uffc6\007\uffc6" +
    "\010\uffc6\014\uffc6\021\uffc6\001\002\000\004\105\265\001" +
    "\002\000\026\027\036\030\044\031\057\032\067\033\050" +
    "\034\041\035\073\036\066\037\062\040\071\001\002\000" +
    "\006\106\267\112\136\001\002\000\004\112\270\001\002" +
    "\000\004\066\271\001\002\000\004\111\272\001\002\000" +
    "\004\005\273\001\002\000\004\112\274\001\002\000\004" +
    "\067\275\001\002\000\004\111\276\001\002\000\004\105" +
    "\277\001\002\000\026\027\036\030\044\031\057\032\067" +
    "\033\050\034\041\035\073\036\066\037\062\040\071\001" +
    "\002\000\006\106\301\112\136\001\002\000\004\112\302" +
    "\001\002\000\004\070\303\001\002\000\004\111\304\001" +
    "\002\000\004\005\305\001\002\000\004\112\306\001\002" +
    "\000\004\071\307\001\002\000\004\111\310\001\002\000" +
    "\004\005\311\001\002\000\004\104\uffc4\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\307\000\020\002\013\003\015\004\014\005\006\006" +
    "\012\022\004\025\003\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\004\016\005" +
    "\006\006\012\022\004\025\003\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\023\001" +
    "\001\000\002\001\001\000\004\010\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\011" +
    "\030\012\032\001\001\000\006\012\160\013\157\001\001" +
    "\000\012\014\037\015\041\016\053\017\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\014\037\015\145\016\053" +
    "\017\033\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\014\134\021\133\001\001\000\002\001\001\000\012\014" +
    "\037\015\114\016\053\017\033\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\020\074\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\014\037\016\113\017\033\001" +
    "\001\000\010\014\037\016\112\017\033\001\001\000\010" +
    "\014\037\016\111\017\033\001\001\000\010\014\037\016" +
    "\110\017\033\001\001\000\010\014\037\016\107\017\033" +
    "\001\001\000\010\014\037\016\106\017\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\014\037\015\121\016\053" +
    "\017\033\001\001\000\012\014\037\015\120\016\053\017" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\017\124\020\123\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\126\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\131\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\137\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\141\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\147\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\152\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\162" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\165" +
    "\001\001\000\002\001\001\000\006\026\171\027\167\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\027\172" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\030" +
    "\176\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\023\227\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\024\260\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\014\134\021\265\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\014\134\021\277\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Lista para guardar los errores sintácticos
    public java.util.ArrayList<ErrorInfo> listaErroresSintacticos = new java.util.ArrayList<>();

    public void syntax_error(Symbol s) {
        String lexema = (s.value != null) ? s.value.toString() : "Fin de archivo";
        String desc = "No se esperaba el componente: " + lexema;
        // En CUP, s.left y s.right guardan la línea y columna respectivamente
        listaErroresSintacticos.add(new ErrorInfo("Sintáctico", desc, s.left, s.right));
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        String lexema = (s.value != null) ? s.value.toString() : "Fin de archivo";
        String desc = "Error irrecuperable cerca de: " + lexema;
        listaErroresSintacticos.add(new ErrorInfo("Sintáctico", desc, s.left, s.right));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= lista_instrucciones 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_instrucciones ::= lista_instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= estrategia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= partida 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= bloque_main 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // estrategia ::= tipo_jugador ID LBRACE accion_inicial bloque_reglas RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // tipo_jugador ::= MAGE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_jugador",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo_jugador ::= WARRIOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_jugador",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // accion_inicial ::= INITIAL COLON accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_inicial",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloque_reglas ::= RULES COLON LBRACKET lista_reglas regla_else RBRACKET 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_reglas",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_reglas ::= lista_reglas regla 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_reglas ::= regla 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // regla ::= IF condicion THEN accion COMMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // regla_else ::= ELSE accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_else",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accion ::= ARCANE_BOLT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // accion ::= FIREBALL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // accion ::= MAGIC_BARRIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // accion ::= HEALING_RUNE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // accion ::= MEDITATE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // accion ::= SLASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // accion ::= HEAVY_STRIKE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // accion ::= SHIELD_BLOCK 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // accion ::= WAR_CRY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // accion ::= REST 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion ::= NOT condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condicion ::= LPAREN condicion RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condicion ::= operando EQEQ operando 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condicion ::= operando NEQ operando 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicion ::= operando LT operando 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion ::= operando GT operando 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= operando LTEQ operando 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= operando GTEQ operando 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // operando ::= INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // operando ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // operando ::= ROUND_NUMBER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // operando ::= TOTAL_ROUNDS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // operando ::= SELF_HEALTH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // operando ::= OPPONENT_HEALTH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // operando ::= SELF_RESOURCE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // operando ::= OPPONENT_RESOURCE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // operando ::= SELF_SCORE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operando ::= OPPONENT_SCORE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // operando ::= RANDOM 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // operando ::= funcion_historial 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // operando ::= accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // operando ::= LBRACKET lista_acciones_secuencia RBRACKET 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operando",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // funcion_historial ::= GET_MOVE LPAREN historial COMMA INTEGER RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_historial",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // funcion_historial ::= LAST_MOVE LPAREN historial RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_historial",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // funcion_historial ::= GET_MOVES_COUNT LPAREN historial COMMA accion RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_historial",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // funcion_historial ::= GET_MOVES_COUNT LPAREN funcion_historial COMMA accion RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_historial",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // funcion_historial ::= GET_LAST_N_MOVES LPAREN historial COMMA INTEGER RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_historial",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // historial ::= SELF_HISTORY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("historial",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // historial ::= OPPONENT_HISTORY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("historial",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // lista_acciones_secuencia ::= lista_acciones_secuencia COMMA accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones_secuencia",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // lista_acciones_secuencia ::= accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones_secuencia",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // partida ::= MATCH ID LBRACE PLAYERS COLON LBRACKET ID COMMA ID RBRACKET ROUNDS COLON INTEGER SCORING COLON LBRACE parametros_scoring RBRACE BONUSES COLON LBRACE parametros_bonuses RBRACE RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("partida",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-23)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // parametros_scoring ::= DAMAGE_POINT COLON INTEGER COMMA HEALING_POINT COLON INTEGER COMMA SUCCESSFUL_DEFENSE COLON INTEGER COMMA VICTORY_BONUS COLON INTEGER COMMA FAILED_ACTION_PENALTY COLON INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros_scoring",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // parametros_bonuses ::= MAGE_COMBO COLON LBRACKET lista_acciones_secuencia RBRACKET COMMA MAGE_COMBO_POINTS COLON INTEGER COMMA WARRIOR_COMBO COLON LBRACKET lista_acciones_secuencia RBRACKET COMMA WARRIOR_COMBO_POINTS COLON INTEGER COMMA LOW_HEALTH_VICTORY COLON INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros_bonuses",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-22)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // bloque_main ::= MAIN LBRACE lista_run RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_main",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // lista_run ::= lista_run instruccion_run 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // lista_run ::= instruccion_run 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // instruccion_run ::= RUN LBRACKET lista_id_partidas RBRACKET WITH LBRACE SEED COLON INTEGER RBRACE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_run",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // lista_id_partidas ::= lista_id_partidas COMMA ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_id_partidas",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // lista_id_partidas ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_id_partidas",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
