    package proyecto1.analizadores;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
        import proyecto1.ast.*;

parser code {:
    //GUARDAR OBJETOS VIVOS 
    public ArrayList<Estrategia> estrategiasAST = new ArrayList<>();
    public ArrayList<Partida> partidasAST = new ArrayList<>();
    public ArrayList<EjecucionRun> listaEjecuciones = new ArrayList<>();

    public java.util.ArrayList<ErrorInfo> listaErroresSintacticos = new java.util.ArrayList<>();

    public void syntax_error(Symbol s) {
        String lexema = (s.value != null) ? s.value.toString() : "Fin de archivo";
        listaErroresSintacticos.add(new ErrorInfo("Sintáctico", "No se esperaba: " + lexema, s.left, s.right));
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        
    }
:}

// ==========================================
// 1. TERMINALES
// ==========================================
terminal String ID, INTEGER, FLOAT;

terminal MAGE, WARRIOR, IF, THEN, ELSE;
terminal MATCH, PLAYERS, ROUNDS, SCORING, BONUSES;
terminal MAIN, RUN, WITH, SEED, INITIAL, RULES;

terminal ARCANE_BOLT, FIREBALL, MAGIC_BARRIER, HEALING_RUNE, MEDITATE;
terminal SLASH, HEAVY_STRIKE, SHIELD_BLOCK, WAR_CRY, REST;

terminal ROUND_NUMBER, TOTAL_ROUNDS, SELF_HEALTH, OPPONENT_HEALTH;
terminal SELF_RESOURCE, OPPONENT_RESOURCE, SELF_SCORE, OPPONENT_SCORE;
terminal SELF_HISTORY, OPPONENT_HISTORY, RANDOM;
terminal GET_MOVE, LAST_MOVE, GET_MOVES_COUNT, GET_LAST_N_MOVES;

terminal DAMAGE_POINT, HEALING_POINT, SUCCESSFUL_DEFENSE, VICTORY_BONUS;
terminal FAILED_ACTION_PENALTY, MAGE_COMBO, MAGE_COMBO_POINTS;
terminal WARRIOR_COMBO, WARRIOR_COMBO_POINTS, LOW_HEALTH_VICTORY;

terminal EQEQ, NEQ, LTEQ, GTEQ, LT, GT;
terminal AND, OR, NOT;
terminal LBRACE, RBRACE, LBRACKET, RBRACKET, LPAREN, RPAREN, COLON, COMMA;

// ==========================================
// 2. NO TERMINALES TIPADOS (AST)
// ==========================================
non terminal inicio, lista_instrucciones, instruccion, bloque_main, lista_run, instruccion_run;
non terminal TipoJugador tipo_jugador;
non terminal Accion accion, accion_inicial, regla_else;
non terminal Regla regla;
non terminal List<Regla> lista_reglas;
non terminal Condicion condicion;
non terminal Expresion operando;
non terminal List<Accion> lista_acciones_secuencia;
non terminal List<String> lista_id_partidas;
non terminal Estrategia estrategia;
non terminal Partida partida;
non terminal FuncionHistorial.Target historial;
non terminal FuncionHistorial funcion_historial;

// ==========================================
// 3. PRECEDENCIA
// ==========================================
precedence left OR;
precedence left AND;
precedence left EQEQ, NEQ, LT, GT, LTEQ, GTEQ;
precedence right NOT;

// ==========================================
// 4. GRAMÁTICA Y ACCIONES SEMÁNTICAS
// ==========================================
start with inicio;

inicio ::= lista_instrucciones ;
lista_instrucciones ::= lista_instrucciones instruccion | instruccion ;
instruccion ::= estrategia | partida | bloque_main ;

// --- ESTRATEGIAS (Construcción Directa) ---
estrategia ::= tipo_jugador:t ID:id LBRACE 
                  INITIAL COLON accion:ai 
                  RULES COLON LBRACKET lista_reglas:lr regla_else:re RBRACKET 
               RBRACE
               {: 
                  Estrategia e = new Estrategia(id, t, ai, lr, re);
                  estrategiasAST.add(e); // Guardamos la estrategia viva
               :}
             ;

tipo_jugador ::= MAGE {: RESULT = TipoJugador.MAGE; :}
               | WARRIOR {: RESULT = TipoJugador.WARRIOR; :}
               ;

lista_reglas ::= lista_reglas:l regla:r {: l.add(r); RESULT = l; :}
               | regla:r {: List<Regla> l = new ArrayList<>(); l.add(r); RESULT = l; :}
               ;

regla ::= IF condicion:c THEN accion:a COMMA {: RESULT = new Regla(c, a); :} ;
regla_else ::= ELSE accion:a {: RESULT = a; :} ;

// --- ACCIONES ---
accion ::= ARCANE_BOLT {: RESULT = Accion.ARCANE_BOLT; :}
         | FIREBALL {: RESULT = Accion.FIREBALL; :}
         | MAGIC_BARRIER {: RESULT = Accion.MAGIC_BARRIER; :}
         | HEALING_RUNE {: RESULT = Accion.HEALING_RUNE; :}
         | MEDITATE {: RESULT = Accion.MEDITATE; :}
         | SLASH {: RESULT = Accion.SLASH; :}
         | HEAVY_STRIKE {: RESULT = Accion.HEAVY_STRIKE; :}
         | SHIELD_BLOCK {: RESULT = Accion.SHIELD_BLOCK; :}
         | WAR_CRY {: RESULT = Accion.WAR_CRY; :}
         | REST {: RESULT = Accion.REST; :}
         ;

lista_acciones_secuencia ::= lista_acciones_secuencia:l COMMA accion:a {: l.add(a); RESULT = l; :}
                           | accion:a {: List<Accion> l = new ArrayList<>(); l.add(a); RESULT = l; :}
                           ;

// --- CONDICIONES Y OPERADORES ---
condicion ::= condicion:i OR condicion:d  {: RESULT = new OperacionLogica(i, "OR", d); :}
            | condicion:i AND condicion:d {: RESULT = new OperacionLogica(i, "AND", d); :}
            | NOT condicion:c             {: RESULT = new OperacionLogica(c, "NOT"); :}
            | LPAREN condicion:c RPAREN   {: RESULT = c; :}
            | operando:i EQEQ operando:d  {: RESULT = new OperacionRelacional(i, "==", d); :}
            | operando:i NEQ operando:d   {: RESULT = new OperacionRelacional(i, "!=", d); :}
            | operando:i LT operando:d    {: RESULT = new OperacionRelacional(i, "<", d); :}
            | operando:i GT operando:d    {: RESULT = new OperacionRelacional(i, ">", d); :}
            | operando:i LTEQ operando:d  {: RESULT = new OperacionRelacional(i, "<=", d); :}
            | operando:i GTEQ operando:d  {: RESULT = new OperacionRelacional(i, ">=", d); :}
            ;

operando ::= INTEGER:v {: RESULT = new Literal(Integer.parseInt(v)); :}
           | FLOAT:v {: RESULT = new Literal(Double.parseDouble(v)); :}
           | ROUND_NUMBER {: RESULT = new Variable(Variable.TipoVar.ROUND_NUMBER); :}
           | TOTAL_ROUNDS {: RESULT = new Variable(Variable.TipoVar.TOTAL_ROUNDS); :}
           | SELF_HEALTH {: RESULT = new Variable(Variable.TipoVar.SELF_HEALTH); :}
           | OPPONENT_HEALTH {: RESULT = new Variable(Variable.TipoVar.OPPONENT_HEALTH); :}
           | SELF_RESOURCE {: RESULT = new Variable(Variable.TipoVar.SELF_RESOURCE); :}
           | OPPONENT_RESOURCE {: RESULT = new Variable(Variable.TipoVar.OPPONENT_RESOURCE); :}
           | SELF_SCORE {: RESULT = new Variable(Variable.TipoVar.SELF_SCORE); :}
           | OPPONENT_SCORE {: RESULT = new Variable(Variable.TipoVar.OPPONENT_SCORE); :}
           | RANDOM {: RESULT = new Variable(Variable.TipoVar.RANDOM); :}
           | accion:a {: RESULT = new Literal(a); :}
           | funcion_historial:f {: RESULT = f;:}
           | LBRACKET lista_acciones_secuencia:lista RBRACKET {: RESULT = new Literal(lista); :}   
           ;  
historial ::= SELF_HISTORY {: RESULT = FuncionHistorial.Target.SELF; :}
            | OPPONENT_HISTORY {: RESULT = FuncionHistorial.Target.OPPONENT; :}
            ;

funcion_historial ::= GET_MOVE LPAREN historial:h COMMA operando:n RPAREN 
                      {: RESULT = new FuncionHistorial(FuncionHistorial.TipoFuncion.GET_MOVE, h, n); :}
                    | LAST_MOVE LPAREN historial:h RPAREN 
                      {: RESULT = new FuncionHistorial(FuncionHistorial.TipoFuncion.LAST_MOVE, h); :}
                    | GET_MOVES_COUNT LPAREN historial:h COMMA accion:a RPAREN 
                      {: RESULT = new FuncionHistorial(FuncionHistorial.TipoFuncion.GET_MOVES_COUNT, h, a); :}
                    | GET_MOVES_COUNT LPAREN funcion_historial:f COMMA accion:a RPAREN     // 👈 NUEVO
                      {: RESULT = new FuncionHistorial(f, a); :}                            // 👈 NUEVO
                    | GET_LAST_N_MOVES LPAREN historial:h COMMA operando:n RPAREN 
                      {: RESULT = new FuncionHistorial(FuncionHistorial.TipoFuncion.GET_LAST_N_MOVES, h, n); :}
                    ;
// --- PARTIDAS (Aplanadas para instanciación directa) ---
partida ::= MATCH ID:id LBRACE 
              PLAYERS COLON LBRACKET ID:p1 COMMA ID:p2 RBRACKET
              ROUNDS COLON INTEGER:r
              SCORING COLON LBRACE 
                 DAMAGE_POINT COLON INTEGER:dp COMMA
                 HEALING_POINT COLON INTEGER:hp COMMA
                 SUCCESSFUL_DEFENSE COLON INTEGER:def COMMA
                 VICTORY_BONUS COLON INTEGER:vb COMMA
                 FAILED_ACTION_PENALTY COLON INTEGER:pen
              RBRACE
              BONUSES COLON LBRACE
                 MAGE_COMBO COLON LBRACKET lista_acciones_secuencia:mc RBRACKET COMMA
                 MAGE_COMBO_POINTS COLON INTEGER:mp COMMA
                 WARRIOR_COMBO COLON LBRACKET lista_acciones_secuencia:wc RBRACKET COMMA
                 WARRIOR_COMBO_POINTS COLON INTEGER:wp COMMA
                 LOW_HEALTH_VICTORY COLON INTEGER:lhv
              RBRACE
            RBRACE 
            {: 
               Partida p = new Partida(id, p1, p2, Integer.parseInt(r),
                           Integer.parseInt(dp), Integer.parseInt(hp), Integer.parseInt(def),
                           Integer.parseInt(vb), Integer.parseInt(pen),
                           mc, Integer.parseInt(mp), wc, Integer.parseInt(wp), Integer.parseInt(lhv));
               partidasAST.add(p);
            :}
          ;

// --- MAIN (Ejecución) ---
bloque_main ::= MAIN LBRACE lista_run RBRACE ;
lista_run ::= lista_run instruccion_run | instruccion_run ;

instruccion_run ::= RUN LBRACKET lista_id_partidas:lista RBRACKET WITH LBRACE SEED COLON INTEGER:s RBRACE 
                    {: 
                       int semilla = Integer.parseInt(s);

                       if (semilla <= 0) {
                           listaErroresSintacticos.add(new ErrorInfo("Sintáctico",
                               "La seed debe ser un entero mayor que cero (valor recibido: " + semilla + ")",
                               sleft, sright));
                           throw new RuntimeException("Error fatal: seed invalida (" + semilla + ").");
                       }

                       listaEjecuciones.add(new EjecucionRun(lista, semilla));
                    :}
                  ;

lista_id_partidas ::= lista_id_partidas:l COMMA ID:id {: l.add(id); RESULT = l; :}
                    | ID:id {: List<String> l = new ArrayList<>(); l.add(id); RESULT = l; :}
                    ;